### ISSUE TITLE
创建任务点击提交后没有响应

### ISSUE THREAD

**Issue by 786744873** [yuzd/Hangfire.HttpJob#100]
大哥好，我在使用过程中点击提交按钮，这个时候没有任何响应，但是实际上任务创建成功了，f12看到js报错，请问是什么原因呢？
![image](https://user-images.githubusercontent.com/24601648/103001234-862d5d00-4567-11eb-90d3-aad6c685fe0a.png)

**Comment by yuzd** [comment]
浏览器缓存清一清看看

**Comment by 786744873** [comment]
> 浏览器缓存清一清看看

清理完，换了好几个浏览器，发现都不行，用的是3.5.3版本的
![image](https://user-images.githubusercontent.com/24601648/103062337-d4cf0b80-45e8-11eb-9067-1dfaffeff276.png)
大哥有qq吗？

**Comment by yuzd** [comment]
如果你之前用过旧的hangfire.httpjob跑过后，可能之前的某个版本有这个js报错问题。但是3.5.3版本是肯定没有的

你 f12后 Ctrl+F5 强刷清楚缓存

或者你百度搜下强制刷缓存，还不行的话加我qq1877682825

**Comment by 786744873** [comment]
大神，我加你了，麻烦通过下

**Comment by 786744873** [comment]
问题解决了，感谢大神的远程协助支持，是因为没有添加以下【UseConsole】代码
```
services.AddHangfire(configuration =>
{
    configuration.UseRedisStorage(new CSRedis.CSRedisClient(Configuration["HFRedis"]),new RedisStorageOptions
    {
        Prefix = "{hf}:",
        Db = 11,
    })
        .UseConsole(new ConsoleOptions
        {
            BackgroundColor = "#000079"
        })
    .UseHeartbeatPage(TimeSpan.FromSeconds(1))
    .UseHangfireHttpJob(new HangfireHttpJobOptions
    {
        DefaultRecurringQueueName = "recurring" //这个是在下面设置的queue列表中的其中一个
    })
    ;
});

```
