### ISSUE TITLE
请问下 如何清理成功的运行日志

### ISSUE THREAD

**Issue by andycheng-jiuluomall** [yuzd/Hangfire.HttpJob#102]
该组件很 早就以demo的形式嵌入了我们自己的.netcore 技术栈
但是一直没有机会在正式项目中使用
主要是因为日志清理的问题
我想请问下有没有公共的日志清理方法
批量的吧 n 天前所有成功的日志清理掉
我们用的是sqlserver 和 redis 

因为没有长时间用过该组件, 所以不是很清楚是否存在某些日志清理机制

**Comment by yuzd** [comment]
hangfire
对于在job执行期间的数据,比如运行时产生的日志 会有一个expire的时间。
这个时间是在hangfire启动的时候配置的。
可以查看我demo里面的配置：https://github.com/yuzd/Hangfire.HttpJob/blob/master/Test/TestHangfire/appsettings.json#L41

我刚刚提交了一个小版本更新：
可以在全局配置里面动态的更改这个参数，但你需要更新下我的组件到最新版；
如何配置请移步：
https://github.com/yuzd/Hangfire.HttpJob/wiki/%E5%85%A8%E5%B1%80%E5%8A%A8%E6%80%81%E9%85%8D%E7%BD%AE%E5%8F%82%E6%95%B0
