### ISSUE TITLE
关于CallbackEL 的后续问题

### ISSUE THREAD

**Issue by andycheng-jiuluomall** [yuzd/Hangfire.HttpJob#104]
用CallbackEL 判定失败后， 在大面板上是算成功的
进入详情才能看到失败

多层的Success 和Fail 设计 是想类似 sqlserver job 的多步骤处理吧 ， 第一步成功之后 第二步酱紫

CallbackEL判定false + SendFail=true 会发邮件出来么？
另外问下Mail如何配置 要逗号切割加用户名密码么？
不知道是不是配的有问题导致错误了之后不发邮件

**Comment by yuzd** [comment]
这里面有图片教程
https://github.com/yuzd/Hangfire.HttpJob/wiki/%E9%85%8D%E7%BD%AE%E9%82%AE%E7%AE%B1%E6%9C%8D%E5%8A%A1%E5%8F%91%E9%80%81job%E6%89%A7%E8%A1%8C%E7%BB%93%E6%9E%9C

**Comment by yuzd** [comment]
先确保配置正确
>用CallbackEL 判定失败后， 在大面板上是算成功的
这个我要确认下，应该callbaclEL失败后大面板应该走到失败才对

失败了你配置了要发失败通知邮件的话 就会触发发邮件

**Comment by yuzd** [comment]
我刚测试了下 
用CallbackEL 判定失败后， 在大面板上是算失败的

![image](https://images4.c-ctrip.com/target/0zb6p120008etmzu3AE02.png)
