### ISSUE TITLE
升级问题 HangfireHttpJobOptions 在3.5.5 中配置改变

### ISSUE THREAD

**Issue by andycheng-jiuluomall** [yuzd/Hangfire.HttpJob#105]
如何替代 RecurringJobTimeZone = TZConvert.GetTimeZoneInfo("Asia/Shanghai")
我猜是酱紫
DefaultTimeZone="Asia/Shanghai"
不知是否正确

另外请问Redis 存储您有没有好的推荐 
我们目前使用的是Tags.Sqlserver(1.7.0)
和Tags.Redis(1.2.2) Redis 这个升级之后无法启动了

**Comment by yuzd** [comment]
DefaultTimeZone="Asia/Shanghai"
对的，可以在全局那里配置

redis存储用https://github.com/marcoCasamento/Hangfire.Redis.StackExchange
