### ISSUE TITLE
options.GlobalSettingJsonFilePath 这句配置代码逻辑有问题？

### ISSUE THREAD

**Issue by cenbiq** [yuzd/Hangfire.HttpJob#106]
https://github.com/yuzd/Hangfire.HttpJob/blob/0488819e302e2babc0889224cee7e16e464f36b1/Server/Hangfire.HttpJob/GlobalConfigurationExtension.cs#L55

为什么是文件不存在才ReadAllText并WriteAllText，导致每次运行都会报一个FileNotFoundException。

**Comment by yuzd** [comment]
多谢你的提醒 ，这个代码不必要了。
