### ISSUE TITLE
请问 参数里的时间如何格式化？

### ISSUE THREAD

**Issue by arvinws** [yuzd/Hangfire.HttpJob#108]
![image](https://user-images.githubusercontent.com/43133223/108483655-ede8f580-72d5-11eb-9365-382317c4cb4a.png)
![image](https://user-images.githubusercontent.com/43133223/108483785-14a72c00-72d6-11eb-90fd-e3b6f35316bd.png)
#{DateTime.Now.AddMinutes(-2).ToString(\"yyyy-MM-dd HH:mm\")}
#{DateTime.Now.AddMinutes(-2)}.ToString(\"yyyy-MM-dd HH:mm\")
试过几种方式，还是不行

**Comment by yuzd** [comment]
你贴一下 运行的日志看下呢

**Comment by arvinws** [comment]
> 你贴一下运行的日志看下呢

![image](https://user-images.githubusercontent.com/43133223/108576250-dd795f00-7357-11eb-95ad-511a14d7eac9.png)
好像是格式不对，试过好多格式，也没成功
＃{DateTime.Now.AddMinutes（-2）.ToString（）}  只有这个可以识别到，但是并没有格式化参数

**Comment by yuzd** [comment]
请试下
```csharp
#{DateTime.Now.AddMinutes(-2).ToString("yyyy-MM-dd HH:mm")}
```

**Comment by arvinws** [comment]
> ```cs
> #{DateTime.Now.AddMinutes(-2).ToString("yyyy-MM-dd HH:mm")}
> ```

![image](https://user-images.githubusercontent.com/43133223/108581024-2ede1a00-7369-11eb-866c-5ab725999201.png)

还是不行

**Comment by yuzd** [comment]
#{DateTime.Now.AddMinutes(-2).ToString('yyyy-MM-dd HH:mm')}

**Comment by arvinws** [comment]
> #{DateTime.Now.AddMinutes(-2).ToString('yyyy-MM-dd HH:mm')}
> 
> ToString()里面的
> 双引号改成单引号

可以了 昨天看报错信息 试过这样写，但是我写成#{DateTime.Now.AddMinutes(-2).ToString(\'yyyy-MM-dd HH:mm\')}  加了转义
谢谢大佬
