### ISSUE TITLE
控制面板中的时间显示能不能本地化

### ISSUE THREAD

**Issue by litdev** [yuzd/Hangfire.HttpJob#109]
RT，执行时间的tips上显示的是这种：Sun, Feb 21, 2021 9:41 AM，这种格式看着有点费劲，能不能本地化改成yyyy-MM-dd HH:mm:ss这种格式？

**Comment by yuzd** [comment]
![image](https://user-images.githubusercontent.com/16083659/108623578-acde1600-747a-11eb-9364-c9b8a2577736.png)

效果如上图

nuget已发布3.5.7 更新后请注意要清楚下浏览器缓存
