### ISSUE TITLE
有没有回调函数，比如执行成功后执行自定义函数，不仅限于发邮件

### ISSUE THREAD

**Issue by i542873057** [yuzd/Hangfire.HttpJob#11]
有没有回调函数，比如执行成功后执行自定义函数，不仅限于发邮件

**Comment by yuzd** [comment]
自定义函数指的是？

**Comment by i542873057** [comment]
> 自定义函数指的是？

比如我想处理自己的逻辑，我想往  kafka中发送处理成功或者失败的通知，或者往REDIS中存入发送的日志

**Comment by yuzd** [comment]
哦 这个你可以用搭配使用 HttpJob.Agent组件，可以自定义你的job处理完之后的的逻辑

https://github.com/yuzd/Hangfire.HttpJob/wiki/HttpJob.Agent%E7%BB%84%E4%BB%B6%E4%BB%8B%E7%BB%8D%E4%BB%A5%E5%8F%8A%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8

**Comment by yuzd** [comment]
如果你说在hangfire.HttpJob里面做手脚的话 ，只有发邮件了没有别的功能。因为hangfire.HttpJob是负责调度的。调度成功或失败支持邮件。
