### ISSUE TITLE
关于任务调度分配的问题

### ISSUE THREAD

**Issue by 3zengzz** [yuzd/Hangfire.HttpJob#110]
请问如果我想要一个任务在相同的服务，部署了2个这种情况去调度，是否支持这个功能，类似于对client进行一个负载，同一个任务，部署2个服务，可以在A服务执行，也可以在B服务执行，相当于内部做了一个负载。

**Comment by yuzd** [comment]
你是用我的agent端功能写job吗？
如果是的话目前agent端还不支持做负载。

如果不是的话，那就是你的api接口自动做负载就行了。比如你用nginx

**Comment by 3zengzz** [comment]
是的用agent写的，好的，感谢回复

**Comment by yuzd** [comment]
正在打算优化这块，望后续关注
