### ISSUE TITLE
钉钉通知可以带日志详情链接吗？

### ISSUE THREAD

**Issue by kinglinglive** [yuzd/Hangfire.HttpJob#111]
![微信图片_20210226130626](https://user-images.githubusercontent.com/50543168/109257599-75cd8300-7833-11eb-8998-2c9f85236c2f.png)

做成链接，直接点击能看到日志详情页

**Comment by yuzd** [comment]
可以的 请参考：

https://github.com/yuzd/Hangfire.HttpJob/wiki/%E5%85%A8%E5%B1%80%E5%8A%A8%E6%80%81%E9%85%8D%E7%BD%AE%E5%8F%82%E6%95%B0

中的关于字段：
CurrentDomain

**Comment by kinglinglive** [comment]
好的
