### ISSUE TITLE
RecurringJobTimeZone 这个时区的怎么没有了

### ISSUE THREAD

**Issue by xt-cui** [yuzd/Hangfire.HttpJob#116]

**Comment by yuzd** [comment]
可以配置默认的时区参数：DefaultTimeZone


https://github.com/yuzd/Hangfire.HttpJob/wiki/%E5%85%A8%E5%B1%80%E5%8A%A8%E6%80%81
%E9%85%8D%E7%BD%AE%E5%8F%82%E6%95%B0

也可以在添加job的时候真的每个job特别设置
