### ISSUE TITLE
Agent能否支持webapi方式上报任务数据

### ISSUE THREAD

**Issue by bao2314483** [yuzd/Hangfire.HttpJob#117]
目前Agent都是通过直接写入DB来上报数据的,这样对于Agent定位非常尴尬,直接穿透到DB层了.
我也看到之前提问也有人提出这方面的需求,不知道作者有没有计划新增这样的需求呢

**Comment by yuzd** [comment]
你有啥idea么

**Comment by bao2314483** [comment]
不知道如果改成webapi目前有什么难点

**Comment by yuzd** [comment]
就是agent调度服务暴露一个api 对吧
这样也是可以的
我努力努力争取早日出个版本

**Comment by bao2314483** [comment]
不是哦，现在Agent是直接把任务状态插入DB的，我意思是Agent与HttpJob之间任务交互是用WebApi方式，而不需要Agent访问DB来实现

**Comment by yuzd** [comment]
和你意思一样 我刚说的是agent调度服务server端 暴露一个api

**Comment by jition1987** [comment]
httpjob支不支持一个队列限制同一个任务每次只会执行一个，
现在有个问题：先查询后新增或修改，数据插入卡不住，数据存在还是插入新数据，代码加锁还是没有用，想请教一下有没有解决方案

**Comment by yuzd** [comment]
jobagent的话有个单例job模式
同时只能执行1次

**Comment by jition1987** [comment]
> @jition1987 jobagent的话有个单例job模式 同时只能执行1次

使用Http接口调用 WebAPI方式 ，可以使用单例模式吗？还是必须加锁？

**Comment by yuzd** [comment]
> > @jition1987 jobagent的话有个单例job模式 同时只能执行1次
> 
> 使用Http接口调用 WebAPI方式 ，可以使用单例模式吗？还是必须加锁？

这个你需要自己在webapi控制了
