### ISSUE TITLE
控制台上的新增|编辑按钮不见了

### ISSUE THREAD

**Issue by weile0769** [yuzd/Hangfire.HttpJob#119]
![image](https://user-images.githubusercontent.com/38940905/112573678-bf57c080-8e27-11eb-84b5-611d16fd9a89.png)
前端抛这个异常
Uncaught DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.

![image](https://user-images.githubusercontent.com/38940905/112573791-f201b900-8e27-11eb-83aa-ca631e687c54.png)

版本是最新版
数据库用的MYSQL

**Comment by yuzd** [comment]
btoa的这个bug我记得修复了呀，难道是我没有发新版本，要不你clone下我的代码的demo看看？没有发版本的 话 我晚上发个
