### ISSUE TITLE
你好，.net core的版本部署到IIS出现无法添加任务的情况，请问有遇到过吗

### ISSUE THREAD

**Issue by HuaFeng520** [yuzd/Hangfire.HttpJob#121]
你好，.net core的版本部署到IIS出现无法添加任务的情况

**Comment by HuaFeng520** [comment]
前端出现Hangfire.Console2 was not properly configured

**Comment by yuzd** [comment]
应该是配置不对，请参考wiki 
https://github.com/yuzd/Hangfire.HttpJob/wiki/00.QickStart
或者你把代码clone下来
对照着demo对比下
