### ISSUE TITLE
周期任务面板中 的bug

### ISSUE THREAD

**Issue by andycheng-jiuluomall** [yuzd/Hangfire.HttpJob#123]
周期任务面板中 当某条周期任务 出错
(应该不是周期任务执行出错, 而是周期任务去获取 hangfire 数据库信息的时候 超时了)
会导致 周期任务面板 由于js bug 而无法加载 周期任务清单
并且特定的周期任务 就不再执行了
但是搜索是能搜索到的 把所有有错误的 周期任务 搜索之后执行一下
周期任务就会继续 按周期执行了 , 并且也能获取周期任务列表了.
抱歉, 因为比较着急 没有留太多的截图 来说明
![image](https://user-images.githubusercontent.com/15645427/116027212-d8ea6300-a686-11eb-9c24-616e8d191f5b.png)
错误信息如下
![image](https://user-images.githubusercontent.com/15645427/116027242-e99ad900-a686-11eb-806d-d6db011d47c0.png)
猜测是因为 hangfire 库也业务数据库在 一起 导致库的 client pool 被占光 导致您编写的hangfire 内部获取周期任务的状态出现了异常

**Comment by yuzd** [comment]
mysql?

**Comment by andycheng-jiuluomall** [comment]
sqlserver

**Comment by yuzd** [comment]
你这种case 重新刷新是不是可以解决？

**Comment by andycheng-jiuluomall** [comment]
刷新无法解决 .. 感觉就是 hangfire 界面发起的查询 由于 有部分结果返回异常 导致了js bug 然后 整个周期任务面板都是失效了

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: ***@***.***>
发送时间: 2021年4月28日 8:19
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [yuzd/Hangfire.HttpJob] 周期任务面板中 的bug (#123)


你这种case 重新刷新是不是可以解决？

―
