### ISSUE TITLE
能否支持调用的WebApi使用Oauth2的方式调用

### ISSUE THREAD

**Issue by itxiaoqiu** [yuzd/Hangfire.HttpJob#126]
WebApi使用的IdentityServer4进行授权验证的，如果能支持调用Api的时候可以先获取AccessToken后再调用WebApi吗？

**Comment by yuzd** [comment]
有2个方案：
1. 用callback功能，类似ajax请求 拿到accessToken后再 掉实际你要的api
2. 或者你本地写一个函数来获取AccessToken 然后注册进去，在你添加HttpJob的时候可以用到SpEl表达动态获取AccessToken

参考文档：
