### ISSUE TITLE
带参数运行报错

### ISSUE THREAD

**Issue by yhEdward** [yuzd/Hangfire.HttpJob#127]
你好！ 
Hangfire.HttpJob.Server.HttpJobDispatcher的Dispatch方法的启动job：startbackgroudjob
跟
Hangfire.HttpJob.Dashboard.DynamicJsDispatcher的Dispatch方法的/httpjob?op=StartBackgroundJob
值对应不上，导致带参数运行报错，第一个少了个n

**Comment by yuzd** [comment]
你是怎么调用的？在dashbord上添加的时候报错了吗？
