### ISSUE TITLE
请教, 执行过程中与前台如何交互

### ISSUE THREAD

**Issue by xibaoning** [yuzd/Hangfire.HttpJob#128]
业务中有耗时任务(大概20分钟执行完成), 期间想返回当前的一些提示信息与进度 给前端用户(用户浏览器),  而不是管理员到后台管理界面去监控, 这部分的实现有什么思路么

**Comment by yuzd** [comment]
你说的这个场景我也有这个需求
所以针对这个需求我开发了agent  中间件

请查阅

https://github.com/yuzd/Hangfire.HttpJob/wiki/03.HttpJob.Agent%E7%BB%84%E4%BB%B6%E4%BB%8B%E7%BB%8D%E4%BB%A5%E5%8F%8A%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8

**Comment by xibaoning** [comment]
看了,还是没太明白呢, 文章里面还是到后台去点击查看了task的信息,   自己的前端页面怎么获取到这些信息呢

**Comment by yuzd** [comment]
自己的前端页面无法获取到把。你的意思是 hangfire dashbord 的console功能 你自己做？

**Comment by xibaoning** [comment]
场景是这样的:&nbsp; 用户在线提交一个耗时任务, 然后让用户可以点击详情页查看任务执行的状态与一些消息,&nbsp; 假设目前的httpclient模块提供一个 GetCurrentStates(jobId)类似的功能,&nbsp; 我自己的程序就可以调用这个接口获取任务的状态了(隔几秒查询一次)


昨晚也研究了下原理, 目前做不到, 只有管理员到后台去查看进度与消息,&nbsp; &nbsp;目前想在httpjob上实现只有自己去查询数据库了, 看了进度条等信息保存到了数据库.&nbsp;&nbsp;
希望未来能通过你的接口用代码方式就能查询到任务信息, 而不是登录到dashbord后台查看




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yuzd/Hangfire.HttpJob"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月9日(星期五) 上午8:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yuzd/Hangfire.HttpJob] 请教, 执行过程中与前台如何交互 (#128)





 
自己的前端页面无法获取到把。你的意思是 hangfire dashbord 的console功能 你自己做？

**Comment by yuzd** [comment]
你说的这个功能目前是hangfire的一个扩展插件叫 console 实现了的事情

也就是说你想要暴露一个console插件的api出来让你的前端调用。
你可以打开dashbord的console来查看他是怎么调用的，看能否移植过去
