### ISSUE TITLE
mysql 版本写代码添加报找不到这个

### ISSUE THREAD

**Issue by cz0004** [yuzd/Hangfire.HttpJob#129]
Failed to process the job '2': an exception occurred.
      System.TypeLoadException: Could not load type 'Hangfire.Tags.Storage.TagsServiceStorage' from assembly 'Hangfire.Tags, Version=1.7.1.0, Culture=neutral, PublicKeyToken=null'.

**Comment by yuzd** [comment]
引入
```
<PackageReference Include="Hangfire.Tags.MySql.Official" Version="1.7.0" />
```

可以查看demo

![image](https://dimg04.c-ctrip.com/images/0v514120008w8nw3n875B.png)
