### ISSUE TITLE
是否支持一下HttpJob.Client删除任务

### ISSUE THREAD

**Issue by flyliao** [yuzd/Hangfire.HttpJob#13]
你好，是否支持一下HttpJob.Client能够远程删除任务？

**Comment by yuzd** [comment]
我研究下

**Comment by yuzd** [comment]
需要讨论下：BackgroundJob 有点特殊 它不是jobname唯一的 

RecurringJob 没问题是 jobName唯一的很好删除

**Comment by yuzd** [comment]
已发布，backgroundjob的话 新增的返回体加了一个jobId。 然后根据这个jobid调用removebackground‘方法

周期性job的话直接根据jobname 调用remove方法就可以了’

**Comment by kasenhoo** [comment]
> 

delete recurring job ,,跟Dashboard上的RecurringJobIdentifier 对应，，而不是 job name
