### ISSUE TITLE
401未授权，不知道为啥，全新的项目，采用redis存储

### ISSUE THREAD

**Issue by LouieGuo** [yuzd/Hangfire.HttpJob#130]
![image](https://user-images.githubusercontent.com/29138525/128857351-1320b8dc-9767-432f-a81b-bb7a8206ce39.png)

**Comment by yuzd** [comment]
![image](https://user-images.githubusercontent.com/16083659/128859082-faafc275-760f-4c27-b7b8-d15d28beb19c.png)

看下这个配置

**Comment by LouieGuo** [comment]
写了
![image](https://user-images.githubusercontent.com/29138525/128859688-f5161bd5-4164-4e1f-ad99-88b0608d5d67.png)

**Comment by yuzd** [comment]
请参考测试demo
![image](https://dimg04.c-ctrip.com/images/0v53a120008wbdhoy1F2E.png)
