### ISSUE TITLE
Cron 项目不支持 秒和年？？还是说可以设置

### ISSUE THREAD

**Issue by LouieGuo** [yuzd/Hangfire.HttpJob#131]

**Comment by yuzd** [comment]
支持秒


请参考 



https://github.com/yuzd/Hangfire.HttpJob/issues/98


https://github.com/yuzd/Hangfire.HttpJob/issues/66

**Comment by yuzd** [comment]
请参考hangfire用的corn组件说明，是支持秒的，不过年的话，我没看到有说明：

https://github.com/HangfireIO/Cronos/#adding-seconds-to-an-expression
