### ISSUE TITLE
MySqlConnector1.0+ 组件里的MySqlConnection命名空间变更

### ISSUE THREAD

**Issue by easycode** [yuzd/Hangfire.HttpJob#133]
使用MySqlConnector1.0+ 找不到MySqlConnection。
查看了源码发现引用的MySqlConnection命名空间不对，需要修正命名空间

**Comment by yuzd** [comment]
在哪个class里面？

**Comment by honorduan** [comment]
> 在哪个class里面？

这个问题我也发现了，是因为原项目Hangfire.HttpJob.Agent.MysqlConsole 依赖的MySqlConnector太低了。需要升级到1.3.10+

**Comment by yuzd** [comment]
好的 我改下

**Comment by yuzd** [comment]
已升级了
