### ISSUE TITLE
docker 中显示的问题

### ISSUE THREAD

**Issue by gywei** [yuzd/Hangfire.HttpJob#134]
你好，我引用了Hangfire.HttpJob nuget 包自己开发系统，配置我选择强制显示中文，结果生成的docker镜像运行后有一部分是中文一部分还是英文，很难受！麻烦指导一下看哪里有问题？
谢谢~

 #region 强制显示中文
            var options = new RequestLocalizationOptions
            {
                DefaultRequestCulture = new RequestCulture("zh")
            };

            app.UseRequestLocalization(options);

            ////强制显示中文
            //System.Threading.Thread.CurrentThread.CurrentUICulture = new System.Globalization.CultureInfo("zh");

            //强制显示中文
            System.Threading.Thread.CurrentThread.CurrentUICulture = new System.Globalization.CultureInfo("zh");

            #endregion

**Comment by yuzd** [comment]
中文的问题 你看下demo里面是怎么用的
