### ISSUE TITLE
最新版bug

### ISSUE THREAD

**Issue by gywei** [yuzd/Hangfire.HttpJob#135]
客户端JobAgent和服务端都是引用的最新的组件，添加周期作业后一直卡在“执行中”，查看状态是Processing.
状态
3 分钟前 (+2ms)Processing
Server:
61A0E59B3641:1
Worker:
JobAgent
+31msSucceeded
Latency:
34ms
Duration:
21ms
+26msProcessing
Server:
61A0E59B3641:1
Worker:
bd118690
+4msEnqueued
Triggered by recurring job scheduler

**Comment by yuzd** [comment]
是不是agent端没有配置storage？

**Comment by yuzd** [comment]
https://github.com/yuzd/Hangfire.HttpJob/wiki/03.HttpJob.Agent%E7%BB%84%E4%BB%B6%E4%BB%8B%E7%BB%8D%E4%BB%A5%E5%8F%8A%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8#%E9%85%8D%E5%90%88hangfire%E8%B0%83%E5%BA%A6%E7%AB%AF%E7%9B%AE%E5%89%8Djobagent%E5%8F%AA%E6%94%AF%E6%8C%81%E4%B8%8B%E9%9D%A2%E4%B8%89%E7%A7%8D
