### ISSUE TITLE
Agent能否扩展一个Oracle的日志输出库出来？

### ISSUE THREAD

**Issue by Corps-Cy** [yuzd/Hangfire.HttpJob#136]
通过Hangfire动态创建的库,其中库结构引用到了序列，在数据量多的情况下会出现 【ORA-02291: 违反完整约束条件 (C##NEWHOPE.FK_JOB_STATE_JOB) - 未找到父项关键字  】错误  我猜想可能是序列的问题，想请教下作者有什么处理方式

**Comment by yuzd** [comment]
oracle的方式我还没有用过,不过看报错是jobstate表和job表的外键导致的，也就是说写如jobstate的jobid列在job表不存在？

**Comment by Corps-Cy** [comment]
![image](https://user-images.githubusercontent.com/38969961/137234935-0737d937-bc1d-4ac3-9f04-abbe0c5feebd.png)
依据mysql的MysqlConsole类库 扩展的oracle版本 全文也就添加这两个表  怀疑是其他地方引起的这个问题
