### ISSUE TITLE
邮件客户端密码是否可以改为非必输项？

### ISSUE THREAD

**Issue by qiang999** [yuzd/Hangfire.HttpJob#14]
您好，邮件客户端密码是否可以改为非必输项？即
 if (string.IsNullOrWhiteSpace(this.Server) || string.IsNullOrWhiteSpace(this.User) || string.IsNullOrWhiteSpace(this.Password)) return null;
这里返回null与try catch后return null好像没有多大区别

**Comment by yuzd** [comment]
没有密码也能发邮件吗？

**Comment by qiang999** [comment]
有些企业邮箱是可以的，我在无密码状态跳过if (string.IsNullOrWhiteSpace(this.Server) || string.IsNullOrWhiteSpace(this.User) || string.IsNullOrWhiteSpace(this.Password))是可以的

**Comment by yuzd** [comment]
那是不是把 if (string.IsNullOrWhiteSpace(this.Server) || string.IsNullOrWhiteSpace(this.User) || string.IsNullOrWhiteSpace(this.Password)) return null;  直接 去掉就好了？

**Comment by qiang999** [comment]
是的，而且我看代码，觉得try catch后return null和这里直接return null，好像差别不是太大

**Comment by yuzd** [comment]
行 我一会发一版

**Comment by qiang999** [comment]
好的，谢谢

**Comment by yuzd** [comment]
这个不是已经改过了吗？

**Comment by qiang999** [comment]
可能还原回去了，我看代码是在这个位置:
![image](https://user-images.githubusercontent.com/15817336/67912258-58978e80-fbc4-11e9-99ed-480375c92c44.png)

**Comment by yuzd** [comment]
咦  我去 我看下

**Comment by yuzd** [comment]
抱歉 改好了 nuget上已更新

**Comment by qiang999** [comment]
好的，十分感谢
