### ISSUE TITLE
为什么这个jq这么大

### ISSUE THREAD

**Issue by ysq5202121** [yuzd/Hangfire.HttpJob#140]
![image](https://user-images.githubusercontent.com/8586973/140675678-e021ce62-8933-4693-acfa-b2878df5474a.png)
放到网络上面很慢

**Comment by ysq5202121** [comment]
增加UseHangfireHttpJob，这个文件加了一倍的大小

**Comment by yuzd** [comment]
![image](https://user-images.githubusercontent.com/16083659/140677765-2fe6a6f6-bd89-46be-a99c-c633451a794e.png)

主要是因为这个的原因

**Comment by ysq5202121** [comment]
这个在线上服务器会影响效率，打开非常慢，是否能够分开几个文件？

**Comment by ysq5202121** [comment]
1.7M下载要3秒。

**Comment by yuzd** [comment]
hangfire的扩展机制里面想要把自定义的js加到hangfire自身的页面
1. 目前的实现方式是官方的推荐方式
不知道有没有别的方式 需要调研下

**Comment by ysq5202121** [comment]
目前暂时通过响应压缩减小了大小
![image](https://user-images.githubusercontent.com/8586973/140693035-e09c0fa2-07ab-48d3-b3c5-e8327757969d.png)

**Comment by yuzd** [comment]
怎么开启的 共享下

**Comment by ysq5202121** [comment]
https://docs.microsoft.com/zh-cn/aspnet/core/performance/response-compression?view=aspnetcore-6.0
AddResponseCompression()
UseResponseCompression()
 Kestrel 服务器当前不提供内置的压缩支持。我用的IIS
