### ISSUE TITLE
请问如何屏蔽单例job 的不能重复执行报错信息

### ISSUE THREAD

**Issue by sad812** [yuzd/Hangfire.HttpJob#147]
如题，能否设置屏蔽单例的报错信息

**Comment by sad812** [comment]
https://github.com/yuzd/Hangfire.HttpJob/wiki/%E5%85%A8%E5%B1%80%E5%8A%A8%E6%80%81%E9%85%8D%E7%BD%AE%E5%8F%82%E6%95%B0

周期性作业-> 全局配置->IgnoreJobAgentSingletonMultExcuteError
已经找到

**Comment by yuzd** [comment]
ok
