### ISSUE TITLE
Ability to specify http headers for httpJob

### ISSUE THREAD

**Issue by brightermatter** [yuzd/Hangfire.HttpJob#15]
Hi, thanks for the great library. It's neatly designed, clean and very useful. Here's my question. How can we specify http headers for the RecurringJob? Sometimes, we need to pass a bearer token as part of the header during http post request. (e.g. bearer token in Authorization header). I'm not sure if there's an easy way to accomplish this, what do you think?

**Comment by brightermatter** [comment]
When I look into your code, I think there can be a simple solution in your PrepareHttpRequestMessage method where you generate the HttpRequestMessage. If we modify the HttpJobItem to accept a list of custom http headers, then these headers can be parsed and added to the http request inside PrepareHttpRequestMessage. Also, this way many other custom headers can be freely added. What do you think, would you accept a PR for this ?

**Comment by yuzd** [comment]
@brightermatter  
```
modify the HttpJobItem to accept a list of custom http headers, then these headers can be parsed and added to the http request inside PrepareHttpRequestMessage
```
good idea! I will be greatefull If you submit a PR.looking foraward to your PR,thanks

**Comment by yuzd** [comment]
@brightermatter  custom http headers is supported now!

**Comment by brightermatter** [comment]
Great job @yuzd, Thx!
