### ISSUE TITLE
发现一个bug

### ISSUE THREAD

**Issue by andycheng-jiuluomall** [yuzd/Hangfire.HttpJob#152]
![c9ca4e78a1c7f5288a7549b1214e8ff](https://user-images.githubusercontent.com/15645427/167079190-d7eeaca1-bff3-4768-868a-93502064dda1.png)
![4f8bc365ad63bfd870276c0a5b31cdf](https://user-images.githubusercontent.com/15645427/167079196-bfc526b1-c1a4-4095-8b8b-230f2bb5a695.png)

这个服务已经停止了25天了 但是我api 的全局log 一直都有捕获到 每小时一次的执行

**Comment by andycheng-jiuluomall** [comment]
版本号是3.5.5

**Comment by andycheng-jiuluomall** [comment]
我天... 我删了这个job 之后 我的日志收集到的信息变成1分钟1次了....
![image](https://user-images.githubusercontent.com/15645427/167085134-49fcc3a7-e30f-4614-9ea7-f21c6d2d3f2d.png)

**Comment by yuzd** [comment]
啥情况

**Comment by andycheng-jiuluomall** [comment]
没事了… 我同事是个傻逼… 把两个任务 链接配成一个了….

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年5月6日 15:41
收件人: ***@***.***>
抄送: ***@***.***>; State ***@***.***>
主题: Re: [yuzd/Hangfire.HttpJob] 发现一个bug (Issue #152)


啥情况

―
