### ISSUE TITLE
使用jobAgent  服务端storge为mysql得时候  agent一直连不上服务端

### ISSUE THREAD

**Issue by peiwen-zhang** [yuzd/Hangfire.HttpJob#153]
![微信截图_20220527010955](https://user-images.githubusercontent.com/19787946/170539434-19f023ef-fcac-4d2d-a489-0c6c907ffad3.png)
初始是连上了 
但是当我执行服务得时候  提示我
![image](https://user-images.githubusercontent.com/19787946/170539626-cc173875-44ef-404d-a3a9-0f0eaf090020.png)
@yuzd 大佬请问一下这个是什么原因造成的

**Comment by yuzd** [comment]
mysql版本多少

**Comment by peiwen-zhang** [comment]
> mysql版本多少

5.7.26

**Comment by yuzd** [comment]
我怀疑和你的mysql设置有关系
可能得加个日志看看sql为啥执行会报错
加qq聊下 1877682825 ？

**Comment by peiwen-zhang** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
最近在忙有事电联！

**Comment by wenfeifei** [comment]
mysql配置文件增加
default-storage-engine=INNODB
innodb_large_prefix=on
innodb_file_format=barracuda
