### ISSUE TITLE
Linux 执行报错

### ISSUE THREAD

**Issue by andycheng-jiuluomall** [yuzd/Hangfire.HttpJob#154]
Recurring job can't be scheduled, see inner exception for details

本地一切正常 linux 上就会报错

**Comment by yuzd** [comment]
有更详细的错误上下文吗

**Comment by andycheng-jiuluomall** [comment]
![92026d631207cad3a8dd78ae476540d](https://user-images.githubusercontent.com/15645427/170978498-bf1c1402-6d59-49f4-ba91-8228c55fc280.png)

**Comment by andycheng-jiuluomall** [comment]
![4e5c788b4cb64ecab86e185547f23d5](https://user-images.githubusercontent.com/15645427/170983157-a23b6914-e016-4871-b174-3a8872f221e2.png)
![2b3542641262edd01c22d79142d46b9](https://user-images.githubusercontent.com/15645427/170983166-79b629d5-3058-4ef4-8895-94ff87bad48a.png)
![953dd776eb376e378c7141aedd895d9](https://user-images.githubusercontent.com/15645427/170983173-036fa570-3e3f-425f-98a7-28a72317d6c2.png)
现在怀疑是不是什么全局配置不对导致hangfirehttpjob 的DateTime.Now 这种的地方出问题了

**Comment by andycheng-jiuluomall** [comment]
![4e9e7c5623985c167ba9af9f0d9134c](https://user-images.githubusercontent.com/15645427/170983489-38669299-8c6d-4926-8ff4-693d5f507241.png)

**Comment by andycheng-jiuluomall** [comment]
![image](https://user-images.githubusercontent.com/15645427/170983882-3b0eb247-ca46-4028-846f-4defe77a512b.png)
感觉还是这个全局的时间配置有问题 导致的
报错的最底层代码 也有传入一个时间

**Comment by andycheng-jiuluomall** [comment]
System.Threading.Thread.CurrentThread.CurrentUICulture = new System.Globalization.CultureInfo("zh-CN");
这行代码加了也不生效...

**Comment by yuzd** [comment]
你的这个应用的这个暴露的接口，你自己用postman测试下能调用 不报错吗

**Comment by andycheng-jiuluomall** [comment]
直接是get 请求 上面图片里有就有啊
在hangfire 里面 DateTime.Now.ToString() 就会有问题

**Comment by yuzd** [comment]
那这个可能是你的环境有关系把

**Comment by yuzd** [comment]
先关了，如果你还有别的线索怀疑是这这个组件有问题再重开
