### ISSUE TITLE
是否支持job分组化管理

### ISSUE THREAD

**Issue by qiang999** [yuzd/Hangfire.HttpJob#16]
您好，我现在看到只有两种权限的面板，只读和管理员，目前是否有基于用户角色管理job的解决方案，若无，后续是否考虑支持？
eg:3个业务部门均只能看到自己部门下的job

**Comment by yuzd** [comment]
这个要结合业务深度扩展hangfire的dashbord了。
目前没有考虑支持，开源项目希望能大家一起扩展
