### ISSUE TITLE
关于使用UseHangfireDashboard每次都会加载一个/Hangfire/js17300

### ISSUE THREAD

**Issue by houwencheng1993** [yuzd/Hangfire.HttpJob#164]
/Hangfire/js17300这个JS文件很大，接近2M，每次都会重新加载，对服务器的宽带有影响，是否能设置浏览器缓存？

**Comment by yuzd** [comment]
默认会有浏览器缓存的吧

**Comment by yuzd** [comment]
参考设置 设置下
https://github.com/yuzd/Hangfire.HttpJob/issues/140
