### ISSUE TITLE
httpjob发送即时任务，header没有带入请求

### ISSUE THREAD

**Issue by 3zengzz** [yuzd/Hangfire.HttpJob#165]
httpjob发送即时任务，header没有带入请求，如下图，header 里token，没有带到http请求heder中
![youdu图片20220721190233](https://user-images.githubusercontent.com/30330939/180199175-c9140fba-16f0-49f3-b29b-f6693e27dba5.png)

**Comment by 3zengzz** [comment]
确认header里的token是有效，请求接口没带上header里的token信息，导致接口认证无效

**Comment by yuzd** [comment]
能从服务接口那边抓到请问报文吗

**Comment by 3zengzz** [comment]
您好，你发的邮件，我已收到，谢谢！

**Comment by 3zengzz** [comment]
> 能从服务接口那边抓到请问报文吗

你好请求如下：
![youdu图片20220725082659](https://user-images.githubusercontent.com/30330939/180672484-7ca3a6ed-069c-48cd-92a5-62df2e34021b.png)

业务接收到的请求如下：
![youdu图片20220725082610](https://user-images.githubusercontent.com/30330939/180672502-909c86ed-51bf-4d9b-9a80-4b3e7b5d6e8b.png)

就是我所提的没有将自定义的header 内容传入，而是将添加job的header 内容一并带到了请求业务接口的header之中，麻烦看看这个问题

**Comment by yuzd** [comment]
加qq聊下1877682825

**Comment by 3zengzz** [comment]
> 877682825

你的QQ设置了问题，在哪里上班，，，我不懂答案，，或者你加我？76595884

**Comment by yuzd** [comment]
![image](https://user-images.githubusercontent.com/16083659/180741464-df6420c1-7ab3-46c0-819a-5e5e405c5c86.png)

非agentjob的话 不用设置BasicName和BasciPassword

设置了的话 会认为用这个basicauth
