### ISSUE TITLE
Enable other authentication schemas

### ISSUE THREAD

**Issue by Depechie** [yuzd/Hangfire.HttpJob#168]
For the moment only Basic Authentication is enabled with HangfireServerPostOption. But our HangFire dashboard is using Microsoft Single Sign On with Azure AD.

Any news if this will also be enabled in the future? Now we can't use this plugin to create jobs.

**Comment by yuzd** [comment]
do you have any suggestion?

**Comment by yuzd** [comment]
sorry about this 
i will reopen it if have any ideas

**Comment by Depechie** [comment]
I guess you need to implement the token flow for oauth with Azure AD ( https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow )
Would be great if this would work

**Comment by yuzd** [comment]
ok, i will check it later
