### ISSUE TITLE
请求出现415，job内部报错不知道原因

### ISSUE THREAD

**Issue by 3zengzz** [yuzd/Hangfire.HttpJob#169]
请求出现415，job内部报错不知道原因

![youdu图片20220823191956](https://user-images.githubusercontent.com/30330939/186145763-16d24751-1865-4eb6-a2ca-6637a979450c.png)
能麻烦帮忙看看吗？实在没找到原因，调用的接口，单独请求可以调通。

**Comment by yuzd** [comment]
application/json 
你拼错啦

![image](https://user-images.githubusercontent.com/16083659/186153234-e75dfad0-3b7a-4e55-b13d-cb51c91ae57f.png)

**Comment by 3zengzz** [comment]
您好，你发的邮件，我已收到，谢谢！
