### ISSUE TITLE
Invoking custom header from dashboard

### ISSUE THREAD

**Issue by brightermatter** [yuzd/Hangfire.HttpJob#17]
Dear @yuzd , thanks again for adding custom header support. I have 2 questions. 

1. How should  we send custom headers from dashboard as plain string? At the backend you deserialize to dictionary, but UI fails to add the job when sending as delimited key value pairs. Here's an example:
![image](https://user-images.githubusercontent.com/15797786/62703929-f11dd880-b9f2-11e9-8433-204303f4af06.png)

2. When the httpJob is executed, there's no way to see the actual result of http response that the invoked service sends, correct? Right now, for example every http request is marked as successful even though actually it got 401 from the server.

Thanks!

**Comment by brightermatter** [comment]
I managed to resolve the serialization by removing the escapes like below. Now the job item is being saved and works perfectly. 
![image](https://user-images.githubusercontent.com/15797786/62709875-eff2a880-b9fe-11e9-8144-3163c24247f7.png)

Now my second question. How can I capture the http response of execution?
Thanks!

**Comment by brightermatter** [comment]
Here's what I want. I want to be able to capture or hook to the results of the HttpContent inside your Excute method. The reason I want this is that, sometimes the response of http job execution needs to be parsed. It might contain valuable data. Maybe, you can persist the http response to hangfire db and another job can check the contents. What do you propose? Thanks

**Comment by yuzd** [comment]
@brightermatter 
how about add another httpjobitem in the request ?
{
"Url":"xxxxx",
"Method":"POST",
{
"Url":"yyyy",
"Method":"POST",
}

}
