### ISSUE TITLE
异常

### ISSUE THREAD

**Issue by zhaozhigang960525** [yuzd/Hangfire.HttpJob#171]
System.Threading.Tasks.TaskCanceledException
The operation was canceled.

System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: 由于线程退出或应用程序请求，已中止 I/O 操作。.
 ---> System.Net.Sockets.SocketException (995): 由于线程退出或应用程序请求，已中止 I/O 操作。

**Comment by yuzd** [comment]
一般这个问题大部分是超时了

**Comment by yuzd** [comment]
请参考

https://github.com/yuzd/Hangfire.HttpJob/issues/107
