### ISSUE TITLE
请教下，JobAgent 中执行的任务如何返回结果？

### ISSUE THREAD

**Issue by andyfoxcs** [yuzd/Hangfire.HttpJob#175]
我通过Hangfire.HttpJob.Client 在调度中心增加了一个任务，任务是通过调度JobAgent去执行的，执行完成后，Success 中HttpCallbackJob 如何把我JobAgent里执行任务的返回内容一并通过这个方式反过来？求指教

**Comment by yuzd** [comment]
我看看

**Comment by yuzd** [comment]
#176 
一类的问题
