### ISSUE TITLE
关于JobAgent 中，在运行时抛出的异常问题

### ISSUE THREAD

**Issue by andyfoxcs** [yuzd/Hangfire.HttpJob#176]
我通过HttpJob.Client 向hangfire调度中心发起任务，并在任务中的 Fail中填写了返回异常时回调服务这个路径，但是在实际运行时，JobAgent中已经抛出了异常，但是在Fail中并未接收到一次信息

HttpJob.Client中Fail信息截图：
<img width="573" alt="image" src="https://user-images.githubusercontent.com/20178697/199141636-9ea98878-2fe6-4ca4-912d-cce07046230b.png">

调度中心任务状态截图：
<img width="908" alt="image" src="https://user-images.githubusercontent.com/20178697/199141304-48e8ec0d-ffbc-4779-8521-0fea7d74751b.png">

JobAgent片段代码截图：
<img width="636" alt="image" src="https://user-images.githubusercontent.com/20178697/199141436-abb8f22c-cf94-4b90-b415-8aa8d612644c.png">

调度中心日志截图：
<img width="730" alt="image" src="https://user-images.githubusercontent.com/20178697/199141530-0c90b161-e1ab-4e5c-b591-3ee4a70a2a34.png">

请问如何返回JobAgent的错误给到Client？

**Comment by yuzd** [comment]
我今天看下这个问题

**Comment by yuzd** [comment]
jobagent这种类型的job
区别于传统的webjob有点不一样，没有把返回值给到调度中心
这个要改一下，等我消息

**Comment by yuzd** [comment]
我想了下，你这个场景其实不需要用jobagent呀，你只需要用普通的webapi即可

jobagent可能需要一直执行的，不存在有返回值一说了
@andyfoxcs

**Comment by yuzd** [comment]
如果你需要在jobagent执行成功 或者失败 去执行别的
完全可以在jobagent里面自己写一些相对应的逻辑也行的

**Comment by yuzd** [comment]
我先关闭了
