### ISSUE TITLE
Agent实现思路，求解答

### ISSUE THREAD

**Issue by tanyo520** [yuzd/Hangfire.HttpJob#177]
1、查看agent源码的时候，发现agent里面的job都是自己用做了一套线程运行机制和扩展的job，这块不能用
Hangfire本身的任务机制去执行么？这块实现原理木有理解，望作者解答下，感谢

**Comment by yuzd** [comment]
server端是hanfire的调度， 当时设计的agent 就是一个运行job的client端来接收server的调度，
他类似于一个webapi
但是区别是他是一个异步的api，支持长时间运行的

因为我想的是server其实已经调度了，Agent只是用来运行而已，不必要内嵌一个Hangfire了
关于这点，我们也可以讨论下，你觉得Agent用Hangfire调度 是在那块使用？

server端发起一个http请求到agent，然后把任务提交给agent的hangfire是吗？
