### ISSUE TITLE
关于暂停任务之后，更改cron表达式

### ISSUE THREAD

**Issue by hezy65** [yuzd/Hangfire.HttpJob#178]
Hello，我这里遇到个问题，通过PauseRecurringJobAsync暂停接口之后，我知道其中的原理是，把现有cron表达式放到另外的字段保存起来，再设置一个不可能执行的cron表达式，来实现任务暂停，但是在暂停之后，我又调用了编辑的接口更改了cron表达式，结果是：任务从暂停的表达式变为启动，并且使用新的表达式，这个时候再次点击暂停/启动，原有存储的旧的表达式会覆盖，导致更改失败，期望的场景是，暂停的情况下，更改表达式，不改变原有暂停状态，更改存储起来的表达式。不知道这是否是合理的场景，求解惑。

**Comment by yuzd** [comment]
好像你这个场景确实有这个问题
我看看

**Comment by hezy65** [comment]
> 好像你这个场景确实有这个问题 我看看

感谢回复

**Comment by yuzd** [comment]
nuget 3.7.2 试试

**Comment by yuzd** [comment]
[hangfire dashbord扩展 禁用job也能展示已设置的cron](https://github.com/yuzd/Hangfire.HttpJob/commit/51415e4802a1b4852312a550cf1b34d79e3573d2)
优化了dashbord
升级到最新版试试

**Comment by hezy65** [comment]
好的，感谢
