### ISSUE TITLE
HttpJob.Client Forbidden bug

### ISSUE THREAD

**Issue by marcelgrilo** [yuzd/Hangfire.HttpJob#18]
hi, i dont know why, but when i try to make a post adding a background job, it returns 403 Forbiden, but when i register by the dashboard it works. 
Is there any thing i am missing?
![image](https://user-images.githubusercontent.com/11089659/65062122-c0b24e00-d951-11e9-9b78-65384130e560.png)

**Comment by yuzd** [comment]
@marcelgrilo  
![image](https://user-images.githubusercontent.com/16083659/65101685-6c63a880-d9fb-11e9-89b0-6ce6ddf91a36.png)
make sure 【IgnoreAntiforgeryToken = true 】

**Comment by marcelgrilo** [comment]
it is already configured, this is ho wmy UseHangfireDashboard is configued

![image](https://user-images.githubusercontent.com/11089659/65154823-8f458b00-da02-11e9-8421-a09700a56c4a.png)

**Comment by yuzd** [comment]
Can you add it on dashbord?
