### ISSUE TITLE
AgentJob自动注册能设置Cron吗，手动很不方便

### ISSUE THREAD

**Issue by my6521** [yuzd/Hangfire.HttpJob#181]

**Comment by yuzd** [comment]
我看看

**Comment by yuzd** [comment]
目前的设计是只有server没有被注册，客户端开启自动注册 且 仅为第一次才会注册
所以如果按照你说的Cron的话，也只能第一次设置，后面如果你在代码中更改也不会更新

因为得防止在dashbord上更新 和 代码中注册的冲突问题

有啥好的建议吗

**Comment by yuzd** [comment]
先关闭 有更好的办法在讨论
