### ISSUE TITLE
httpjob中按钮请求后端如何将请求地址加入前缀路径

### ISSUE THREAD

**Issue by m344739968** [yuzd/Hangfire.HttpJob#182]
hangfire dashboard地址：https://xxxx.xxxx.com.cn/group-order-job-service/job，其中group-order-job-service是域名下的相对路径
hangfire中可以通过配置来给路径加入前缀地址
app.UseHangfireDashboard("/job", new DashboardOptions
{
    IgnoreAntiforgeryToken = true,
    AppPath = hangFireOption.DashboardAppPath
    PrefixPath = "/group-order-job-service"
});
但是httpjob相关的请求如何配置？
![image](https://user-images.githubusercontent.com/16041240/215367573-189300a6-a390-440c-80b3-40fc09a9782c.png)

**Comment by yuzd** [comment]
![image](https://user-images.githubusercontent.com/16083659/215368335-03267c05-4838-44cd-b85b-9096cb5aa4ab.png)
![image](https://user-images.githubusercontent.com/16083659/215368348-4e99f6b8-d50e-473d-8d24-d21cb88ddeb8.png)

得兼容一下dashbord的PrefixPath

晚点我看看，或者你可以帮忙给个PR

**Comment by yuzd** [comment]
https://github.com/yuzd/Hangfire.HttpJob/pull/183
