### ISSUE TITLE
暂停了定时任务，还是会重试？

### ISSUE THREAD

**Issue by WangJunZzz** [yuzd/Hangfire.HttpJob#19]
![image](https://user-images.githubusercontent.com/25657426/66797461-68b13c00-ef3d-11e9-96bb-24c67f4ef642.png)
![image](https://user-images.githubusercontent.com/25657426/66797478-71a20d80-ef3d-11e9-9003-a1f36b34d494.png)

**Comment by WangJunZzz** [comment]
![image](https://user-images.githubusercontent.com/25657426/66797942-f6d9f200-ef3e-11e9-9234-e72c43beebba.png)

**Comment by mswinner** [comment]
调度是会调度的 但是在方法执行前的拦截器里面直接回return掉

暂停后建议不调度了

**Comment by WangJunZzz** [comment]
这个可以在配置文件中配置码？

**Comment by yuzd** [comment]
> 调度是会调度的 但是在方法执行前的拦截器里面直接回return掉
> 
他说的是对的

@WangJunZzz

**Comment by WangJunZzz** [comment]
但是一致在跑，觉得有点怪。

**Comment by yuzd** [comment]
> 但是一致在跑，觉得有点怪。

因为暂停这个机制对于一个hangfire 而言是没有这个功能的，所以hangfire还是会一直调度的。只不过拦截器直接把return掉了

**Comment by yuzd** [comment]
@WangJunZzz  如果你不想让hangfire调度 可以修改周期性job 把 Cron 的值改成空。就不会调度了，只能手动触发调度

**Comment by WangJunZzz** [comment]
@yuzd 嗯嗯 这个也可以

**Comment by ctacy** [comment]
我问一个问题：我添加的周期性任务，经过测试发现必须一直把 localhost/job 这个页面打开才能准时执行；比如我 设置了 00：00的任务。到了时间点并没有执行，等到早上我登入job以后才立即执行了一次，这个是怎么回事呢？
