### ISSUE TITLE
blazor server模式下。多个任务提交异常

### ISSUE THREAD

**Issue by Seanxwy** [yuzd/Hangfire.HttpJob#192]
blazor server模式下。多个任务提交异常。提交任务无法正常返回，然后导致后面主线程和await的任务无法执行。在hangfires上可以看到提交的第一个任务是正常的。

**Comment by yuzd** [comment]
有错误日志吗？

**Comment by Seanxwy** [comment]
![image](https://github.com/yuzd/Hangfire.HttpJob/assets/15828095/691b425d-b540-4826-ad0a-e5d7b28e456d)
我有使用try catch，并没有抛出异常。

**Comment by yuzd** [comment]
是result.IsSuccess = false的话 你看一下 result.ErrMessage

**Comment by Seanxwy** [comment]
不会走到result.isSuccess =false。直接挂了。也没有走到catch

**Comment by yuzd** [comment]
还会有这种情况
有能再现的demo吗？

**Comment by Seanxwy** [comment]
更新了？没有尝试，我现在只能放到contorller用httpclient来处理了。回头我可以再试一下。

**Comment by yuzd** [comment]
blazor不是很熟悉，不确定是不是header头没有带上auth
有可以调试的话应该能很快定位到问题
