### ISSUE TITLE
是否可以保存上一次运行的Data,并在下一次运行中获取到这个数据。

### ISSUE THREAD

**Issue by AdamvvYau** [yuzd/Hangfire.HttpJob#193]
HttpJob可以支持SpringEL，那么是否可以保存上一次运行的Data,并在下一次运行中获取到这个数据？或者如何做可以达到同样的效果？
想在下次运行根据上次的参数自动生成新的参数。

**Comment by yuzd** [comment]
可以参考下这个issue的解决方案：

https://github.com/yuzd/Hangfire.HttpJob/issues/185

想在下次运行根据上次的参数自动生成新的参数。
—> 自定义一个函数专门做这个事情，然后把请求的body作为参数传到你这个自定义函数
比如你把body解析生成一个东西存在缓存中，下一次运行就直接拿？
