### ISSUE TITLE
时间显示问题

### ISSUE THREAD

**Issue by Jxika** [yuzd/Hangfire.HttpJob#196]
执行菜单中时间显示问题：
![image](https://github.com/yuzd/Hangfire.HttpJob/assets/39694137/897d40ba-e8a8-43a7-86cf-e557a25fe77a)

**Comment by yuzd** [comment]
建议这里应该显示怎样的？

**Comment by Jxika** [comment]
> 建议这里应该显示怎样的？

下午启动1点，却显示凌晨3点

**Comment by Jxika** [comment]
> 建议这里应该显示怎样的？

下午1点启动的，却显示凌晨3点

**Comment by yuzd** [comment]
是不是重试的job？
我测试没有再现这个问题
