### ISSUE TITLE
 err:x-job-agent-action in headers can not be empty!

### ISSUE THREAD

**Issue by wanglei8888** [yuzd/Hangfire.HttpJob#198]
项目是 .net6 我分别注册了一个调度端在: localhost:5000 和服务端localhost8080,但是无法调用，下面是报错信息
![image](https://github.com/yuzd/Hangfire.HttpJob/assets/58056950/bf216072-4ab0-46d9-baf0-89d30a63e51d)
下面是注册信息
![image](https://github.com/yuzd/Hangfire.HttpJob/assets/58056950/2cfc27fa-c7dd-413d-b395-cd26193eaf16)
![image](https://github.com/yuzd/Hangfire.HttpJob/assets/58056950/780eefea-d063-4f61-ad83-de32330ce350)
![image](https://github.com/yuzd/Hangfire.HttpJob/assets/58056950/0637de8d-4e73-4ed8-968c-b3f035a28311)
![image](https://github.com/yuzd/Hangfire.HttpJob/assets/58056950/e82843cc-cea8-4e1d-81cd-ed878d14ed8e)
请问应该如何解决

**Comment by wanglei8888** [comment]
![image](https://github.com/yuzd/Hangfire.HttpJob/assets/58056950/26055197-c921-489e-8d2b-c36222b8877b)

**Comment by yuzd** [comment]
你不能像添加普通http api的方式去添加agent方式的job

请查看文档：
https://github.com/yuzd/Hangfire.HttpJob/wiki/03.HttpJob.Agent%E7%BB%84%E4%BB%B6%E4%BB%8B%E7%BB%8D%E4%BB%A5%E5%8F%8A%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8

**Comment by yuzd** [comment]
agent有自动注册功能的
