### ISSUE TITLE
httpjob只会在启动项目注册

### ISSUE THREAD

**Issue by wanglei8888** [yuzd/Hangfire.HttpJob#199]
![image](https://github.com/yuzd/Hangfire.HttpJob/assets/58056950/4e5ca295-ed57-4e9b-84fd-d58c0ceab759)
![image](https://github.com/yuzd/Hangfire.HttpJob/assets/58056950/bdc422d5-8f23-4439-bc66-8d7d1b6a1ece)
如图所示我有两个job,但是项目启动的时候只会注册store里面的Job， 项目关系为store引用service 请问应该如何解决

**Comment by yuzd** [comment]
参考昨天我发的那个wiki
可以手动添加的

**Comment by wanglei8888** [comment]
请问是现阶段只支持启动项目自动注册吗?

**Comment by yuzd** [comment]
你按照规则来可以手动注册的
有详细教程
https://github.com/yuzd/Hangfire.HttpJob/wiki/03.HttpJob.Agent%E7%BB%84%E4%BB%B6%E4%BB%8B%E7%BB%8D%E4%BB%A5%E5%8F%8A%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8

**Comment by wanglei8888** [comment]
我了解你的意思,我也知道可以手动注册，我的问题是关于自动注册这一块。 所以自动注册暂时只支持在启动项目自动注册时这个意思吗？

**Comment by yuzd** [comment]
可以用这个api来自己指定class type注册
https://github.com/yuzd/Hangfire.HttpJob/blob/master/Agent/Hangfire.HttpJob.Agent/Config/JobAgentServiceConfigurer.cs

**Comment by wanglei8888** [comment]
好滴，万分感谢。
