### ISSUE TITLE
redis 数据库消息不会失效，导致服务器内存给占满

### ISSUE THREAD

**Issue by sonicshadow** [yuzd/Hangfire.HttpJob#201]
我使用了reids数据和JobAgent方式实现定时任务。
对于这个项目来说定时任务的记录不重要，不需要长期保存。我想设置TTL让记录自然消失。
修改了appsettings.json的JobExpirationTimeoutDay后 成功的Job有TTL了，但是失败的job还是无限期。
我现在希望失败的job也有TTL，要怎么写。

[AutomaticRetry(Attempts = 0, OnAttemptsExceeded = AttemptsExceededAction.Delete)]
public class MyJob : JobAgent

这样写没有效果，请问正确的写法该怎么写

**Comment by yuzd** [comment]
晚点我看看
