### ISSUE TITLE
使用agent.job 想先登陆获取用户token,再带token去访问agent.job,无法实现

### ISSUE THREAD

**Issue by wanglei8888** [yuzd/Hangfire.HttpJob#202]
![image](https://github.com/yuzd/Hangfire.HttpJob/assets/58056950/73bceeff-1ccb-4659-b1af-371946f4f0fa)

![image](https://github.com/yuzd/Hangfire.HttpJob/assets/58056950/fa3928b6-8af5-4cdc-aa18-1ad36cfb6884)
配置信息:
{
  "Success": {
    "Url": "http://localhost:5566/jobagent",
    "Method": "Post",
    "Data": "",
    "ContentType": "application/json",
    "Timeout": 20000,
    "QueueName": "recurring",
    "AgentClass": "SRM.Application.Job.PerformanceAppraisalJob,SRM.Application",
    "Headers": {
      "Authorization": "#{#parent.data}"
    },
    "BasicUserName": "admin",
    "BasicPassword": "test"
  },
  "RecurringJobIdentifier": "绩效考核定时任务",
  "Url": "http://localhost:5566/login",
  "Method": "Post",
  "Data": "{\"userName\":\"test-admin\",\"password\":\"123456\"}",
  "ContentType": "application/json",
  "Timeout": 20000,
  "DelayFromMinutes": 15,
  "Cron": "0 0 31 2 *",
  "JobName": "绩效考核定时任务",
  "QueueName": "recurring",
  "AgentTimeout": 0,
  "SendSuccess": false,
  "SendFail": false,
  "Mail": "",
  "EnableRetry": false,
  "RetryTimes": 0,
  "BasicUserName": "admin",
  "BasicPassword": "test",
  "Headers": {}
}
日志:
![image](https://github.com/yuzd/Hangfire.HttpJob/assets/58056950/a3242939-6e02-4fa1-8fc2-69137b3124b0)

**Comment by yuzd** [comment]
![image](https://github.com/yuzd/Hangfire.HttpJob/assets/16083659/755d4d87-b933-4890-8a7f-4bcbd8b6a30f)

**Comment by wanglei8888** [comment]
请问可以再job.agent里面打印表头这种操作吗？或者带入的参数

**Comment by wanglei8888** [comment]
![image](https://github.com/yuzd/Hangfire.HttpJob/assets/58056950/7bbce156-575f-4f50-9ee1-7596e2f82149)
这个里面

**Comment by yuzd** [comment]
你是希望拿什么信息呢？
有试过从jobContext里面拿param吗

**Comment by wanglei8888** [comment]
我是希望拿从父接口传入的信息，检测是否传正确得值例如:
![Uploading image.png…]()

**Comment by wanglei8888** [comment]
![image](https://github.com/yuzd/Hangfire.HttpJob/assets/58056950/3f4dde43-4a2a-482c-b193-622b31b83297)

**Comment by yuzd** [comment]
jobContext对象里面有个Headers  你试试

**Comment by wanglei8888** [comment]
![image](https://github.com/yuzd/Hangfire.HttpJob/assets/58056950/b1e169ce-8429-4d32-ad14-2e45f59d0057)
获取没问题了
再冒昧的请教一个问题,我查询数据添加了sqlsugar的过滤器，会为所有表格添加一个过滤条件，但是这个过滤条件是从jwt鉴权的信息里面获取,但是我看job.agent 带上头部也不会获取到鉴权信息,job.agent是不是不是不是通过http方式实现的？事通过什么方式实现的? 请问我这个问题，有方法解决吗？

**Comment by wanglei8888** [comment]
![image](https://github.com/yuzd/Hangfire.HttpJob/assets/58056950/ca967b5c-711b-417f-84a6-ef6b5b008bf2)

**Comment by wanglei8888** [comment]
![image](https://github.com/yuzd/Hangfire.HttpJob/assets/58056950/1a56775b-d84e-4ace-a11b-eeefe6332d29)

**Comment by yuzd** [comment]
hangfire是通过http方式请求调度agent的

如果你在agent上加过滤器的话 可能你需要把你的过滤器middlerware的顺序放在hangfireagent的middlerware的签名才会生效把。
https://github.com/yuzd/Hangfire.HttpJob/blob/master/Agent/Hangfire.HttpJob.Agent/JobAgentMiddleware.cs

**Comment by wanglei8888** [comment]
![image](https://github.com/yuzd/Hangfire.HttpJob/assets/58056950/b7f88b52-ee5d-4697-b893-0746a794a843)
你如果有时间的话,https://github.com/wanglei8888/HuanTian  这里有demo（HuanTian.Store项目），里面有我的注册顺序

**Comment by wanglei8888** [comment]
即使放最后注册中间件也无法获取,请问有合适的解决方案推荐吗？

**Comment by yuzd** [comment]
agent的请求接收是封装在一个middreware的
如果你的filter 能作用在这一层之前拿到请求进行处理 应该是可行的

**Comment by wanglei8888** [comment]
![1702014396212](https://github.com/yuzd/Hangfire.HttpJob/assets/58056950/db4c70ed-4e9d-43eb-aa4d-e5d5f3d192b1)
![1702014396218](https://github.com/yuzd/Hangfire.HttpJob/assets/58056950/59ef9116-8350-4938-99ad-dea81187e565)
因为有默认的Authorization,替换成其他的就可以了。
![1702014398125](https://github.com/yuzd/Hangfire.HttpJob/assets/58056950/d2b2ebc6-d0db-4ab3-9dde-844845f02f28)
![1702014396224](https://github.com/yuzd/Hangfire.HttpJob/assets/58056950/91a4efa2-7a9f-482e-937d-ccbc6eb7126a)
明明依赖注入的时候有值，但是进入方法之后，IHttpContextAccessor 值又为null了，不知道为什么

**Comment by yuzd** [comment]
原来被替换了

依赖注入没有，感觉像是HttpContextAccessor的使用方式有点问题
你参考下
https://stackoverflow.com/questions/52927463/access-httpcontextaccessor-from-startup-cs-in-net-core-webapi

**Comment by wanglei8888** [comment]
我看了下源码,开了一个线程去执行这个任务,但是依赖注入被替换了. 这应该算是程序BUG把？ 你提供的方法，解决不了,因为IHttpContextAccessor 为null，如何调用也是null

**Comment by wanglei8888** [comment]
demo,我发你qq邮箱了

**Comment by yuzd** [comment]
好的 我看下

**Comment by yuzd** [comment]
agent的job收到了server的调度的时候，会开启一个新的线程去执行，只有这样才能执行长时间运行的任务，是这么设计的
至于为啥IHttpContextAccessor 对象的HttpContext为啥为null
在Construct构造方法的时候你看是有值的。
但是由于是异步执行job的OnStart方法，
执行构造方法的http请求线程已经处理完了，导致HttpContext变成null

不建议在Onstart方法里面去读取IHttpContextAccessor.HttpContext
你需要用到header信息应该直接从JobContext上下文中去拿

**Comment by wanglei8888** [comment]
多谢了，作者大大！
我用的sqlSugar租户过滤器,每次查询都需要获取当前登陆用户的租户、 那看来使用httpjob更好一些，能完全契合框架,jobAgent不太适合我这种

**Comment by yuzd** [comment]
好的

**Comment by wanglei8888** [comment]
我还发现一个问题、回调函数执行的方法里打印无法生效
![image](https://github.com/yuzd/Hangfire.HttpJob/assets/58056950/424c1796-7618-4744-9762-a8b87eb48435)
![image](https://github.com/yuzd/Hangfire.HttpJob/assets/58056950/74f22a6e-3ac8-4350-b3cc-9e36a537226f)
![image](https://github.com/yuzd/Hangfire.HttpJob/assets/58056950/05c2a42d-fb08-4ba4-83f8-71a752068631)
