### ISSUE TITLE
語系顯示問題

### ISSUE THREAD

**Issue by Bean90638** [yuzd/Hangfire.HttpJob#203]
我打算新增繁體中文語系檔，先使用現有的Strings.es.resx測試切換語系有以下問題
 
1. 畫面上的文字並不是全部都有切換
發現元件上的文字依然是中文，於JS上`CloseButtonName`抓到的也是`关闭`
![image](https://github.com/yuzd/Hangfire.HttpJob/assets/52120833/1f6e183a-1dc5-4187-9982-da831aa8899e)
但是切換到Cron頁面有正常切換語系
![image](https://github.com/yuzd/Hangfire.HttpJob/assets/52120833/ad6c84f7-a86f-41f2-8148-74b093df56c0)
 
2. 部分文字不是使用語系檔
目前是藉由別的文字來間接判斷，應藉由語系檔案(resx)顯示文字
![image](https://github.com/yuzd/Hangfire.HttpJob/assets/52120833/4dbdfda6-5410-4360-9bdf-2641da3d0de5)
 
3. Strings.es.resx 內容拿去翻譯判斷比較像英文(en)，但我沒學過西班牙語(es)不是很確定
 
 
附上我建立的測試專案連結供參考
https://github.com/Bean90638/HangfireTest.git

**Comment by yuzd** [comment]
感谢你的pr
nice job
