### ISSUE TITLE
Hangfire.Tags Deprecated, update to https://github.com/face-it/Hangfire.Tags

### ISSUE THREAD

**Issue by maxiar** [yuzd/Hangfire.HttpJob#204]
Hi! Excelent works! I want to use Tags, but found that the current hangfire.tags has been deprecated and a new one is recommended https://github.com/face-it/Hangfire.Tags, the question is the HttpJobs is compatible with that? Can you upgrade it to support, please?

Thanks!

**Comment by yuzd** [comment]
okay , i will update on this weekend.

**Comment by yuzd** [comment]
done 
new version: 3.8.2
