### ISSUE TITLE
Missing HttpJobs Results on UI [Updated]

### ISSUE THREAD

**Issue by maxiar** [yuzd/Hangfire.HttpJob#208]
Hi! I don't know what happens in the latest versions, that the httpjobs response is missing in the UI, please check the screenshot...
 I'm not sure if a issue of HttpJobs or the FaceIT.Hangfire.* .. Can you help me?
 
<img width="944" alt="image" src="https://github.com/yuzd/Hangfire.HttpJob/assets/974115/23f6f13a-a7ac-4913-b9d6-609bdcc607ba">

**Comment by maxiar** [comment]
I made some test.. I commented the FaceIT.Hangfire.Tags behavior, and neither shows the success or error response ...  
How to do to show the real http response contents when a job run success or fail... 

For example I hope this response when a jobs fails, same as postman output....

<img width="904" alt="image" src="https://github.com/yuzd/Hangfire.HttpJob/assets/974115/7a502b35-ba40-457f-a582-c483b1622442">

And then everything was success something like that:

<img width="883" alt="image" src="https://github.com/yuzd/Hangfire.HttpJob/assets/974115/4e30030e-cae6-463f-b206-7ec6aaaa3e23">

Did I miss some configuration or some filter? What is your opinion?

Thanks in advanced.

**Comment by yuzd** [comment]
what's your verion of Hangfire?

https://github.com/yuzd/Hangfire.HttpJob/issues/207#issuecomment-1922624177

**Comment by maxiar** [comment]
I attached all hangfire.* package version... ![image](https://github.com/yuzd/Hangfire.HttpJob/assets/974115/08ad4648-b88e-4f1d-b4a4-e27ac65a6d17)

Thanks!

**Comment by maxiar** [comment]
Hi! Any news? Any workaround ?

**Comment by yuzd** [comment]
i just released a new version, upgrade  and try ~
please  let me kown if this issue not solved

**Comment by maxiar** [comment]
Hi! I Updated to the latest release, but this issue was not resolved.. :(

Updated versions:

        <PackageReference Include="FaceIT.Hangfire.Tags.SqlServer" Version="1.9.0-beta.3" />
        <PackageReference Include="Hangfire" Version="1.8.12" />
        <PackageReference Include="Hangfire.Console" Version="1.4.3" />
        <PackageReference Include="Hangfire.Console.Extensions" Version="1.0.5" />
        <PackageReference Include="Hangfire.HttpJob" Version="3.8.5" />
        <PackageReference Include="Hangfire.HttpJob.Client" Version="1.2.9" />
        <PackageReference Include="Hangfire.MySqlStorage" Version="2.0.3" />
        <PackageReference Include="Hangfire.PostgreSql" Version="1.20.5" />
        <PackageReference Include="Hangfire.SQLite" Version="1.4.2" />
        <PackageReference Include="MailKit" Version="4.5.0" />
        
Any idea?

**Comment by yuzd** [comment]
could you test my sqlserver demo project ?

https://github.com/yuzd/Hangfire.HttpJob/tree/master/Test/TestSqlserver

**Comment by maxiar** [comment]
Hi! I made a test, it's works success in your version and bad in mine:

Your...

<img width="935" alt="image" src="https://github.com/yuzd/Hangfire.HttpJob/assets/974115/556aa5be-9930-4b21-b223-ca7e6dd28e73">


Mine...

<img width="946" alt="image" src="https://github.com/yuzd/Hangfire.HttpJob/assets/974115/44975eca-5af8-4484-8702-5a54199c8f91">

Something in my version is wrong... note that I'm using the FaceIT.TAG integration... but I already disabled it an continue working bad...

Any suggestion? Regards!

**Comment by yuzd** [comment]
https://github.com/HangfireIO/Hangfire/issues/2308

disable tag

**Comment by maxiar** [comment]
Fotgot it! I resolved! Simple Add this mising using, I'm an stupid! Sorry....

<img width="789" alt="image" src="https://github.com/yuzd/Hangfire.HttpJob/assets/974115/82bccfe0-3f57-4744-8a10-e7b2a33639a0">

**Comment by yuzd** [comment]
okay
