### ISSUE TITLE
你好，我有一个疑问,关于队列名称的。

### ISSUE THREAD

**Issue by WangJunZzz** [yuzd/Hangfire.HttpJob#21]
1.默认的队列名称是Default.假如我新增一个周期性作业queuename="default001",这个任务是不会执行的，需要在            
``` csharp
            app.UseHangfireServer(new BackgroundJobServerOptions()
            {
               // 写死了
                Queues = new[] { "default", "default001" }
            });
```
有没有其他办法？或者添加任务的时候队列不存在，则添加？

**Comment by yuzd** [comment]
有时间的话 你可以先调查下hangfire 能支持代码创建queue吗？

**Comment by WangJunZzz** [comment]
好的

**Comment by yuzd** [comment]
我这几天有点忙不在国内，如果hangfire可以用代码创建queue，你说的这个功能就很好实现了

**Comment by WangJunZzz** [comment]
我没有具体去看hangfire是否可以创建queue，我先去了解一下。

**Comment by yuzd** [comment]
看了下hangfire.core的源码关于初始化queue的逻辑，
是启动hangfire的时候 指定的queue会被包装成一个对象反序列化json字符串存入db（如下图）。
不支持代码运行时创建新的queue

![image](https://images4.c-ctrip.com/target/zb0e1a0000018dgme9011.png)

![image](https://user-images.githubusercontent.com/16083659/68065414-f1b0db80-fd63-11e9-8dec-2e1e9e1de9f6.png)

 我已经新提交了一个版本 支持backgroundjob指定 queue名称
