### ISSUE TITLE
3.8.4 nuget上包有问题

### ISSUE THREAD

**Issue by znw333** [yuzd/Hangfire.HttpJob#212]
问题点：
Test/Mysql/MysqlHangfire/HangfireCollectionExtensions.cs
169行：app.UseHangfireHttpJob().UseHangfireDashboard(hangfireSettings.StartUpPath, dashbordConfig);
无法获取到UseHangfireHttpJob方法
![image](https://github.com/yuzd/Hangfire.HttpJob/assets/29272193/134e8663-6206-495d-8a45-58a06941d02d)

ILSpy也读取不到这个方法

nuget上下载到的是3.7.5
![image](https://github.com/yuzd/Hangfire.HttpJob/assets/29272193/2024dc6e-b24c-4f90-8563-e7dd51554ca7)

**Comment by yuzd** [comment]
并没有发现你说的这个错误哦
![image](https://github.com/yuzd/Hangfire.HttpJob/assets/16083659/11849d86-5a87-40b4-9cfb-85fd79965834)

**Comment by yuzd** [comment]
先关闭issue，有问题你在反馈
