### ISSUE TITLE
Problem adding recurring task from dashboard

### ISSUE THREAD

**Issue by gilsoncabacazzo** [yuzd/Hangfire.HttpJob#22]
I have this problem adding a new recurring task using the httpjob extension.
I would be grateful if you could help me
Thank you
Regards
![1](https://user-images.githubusercontent.com/56260092/67283955-057a5900-f4ab-11e9-9aef-97c22e11fe0a.png)
![2](https://user-images.githubusercontent.com/56260092/67283959-08754980-f4ab-11e9-9e97-300228fda38b.png)

**Comment by yuzd** [comment]
If you want to run it every 2 seconds
Try:
0/2 * * * * ?

**Comment by gilsoncabacazzo** [comment]
It worked friend, anyway the frequency should be every two minutes and using the cron generator is equal to 2 * * * *
Thank you very much for your answer
Regards
