### ISSUE TITLE
Problem with recurring task frequency

### ISSUE THREAD

**Issue by gilsoncabacazzo** [yuzd/Hangfire.HttpJob#23]
According to the cron expression generated every two minutes, it is 2 * * * *, but when registering a new task, a value greater than two minutes appears in the next execution column.
Is there a problem with the generated cron expression?
Thanks for your help forever
Regards
![1](https://user-images.githubusercontent.com/56260092/67393989-d8e14280-f579-11e9-8002-db5f8850a487.png)

**Comment by yuzd** [comment]
you can check the cron:

![image](https://user-images.githubusercontent.com/16083659/67568348-8f9e1800-f75e-11e9-8be1-43a8731ee3fc.png)

**Comment by gilsoncabacazzo** [comment]
I send you what the generator cron returns
![image](https://user-images.githubusercontent.com/56260092/67568914-e591a200-f703-11e9-8a01-0b01d31ab136.png)

**Comment by yuzd** [comment]
so , your cron not means every 2 minutes.

**Comment by yuzd** [comment]
![image](https://user-images.githubusercontent.com/16083659/67570296-924f3c00-f763-11e9-93b5-cbb479c07222.png)

if you want every 2 minutes , you can check this:
![image](https://user-images.githubusercontent.com/16083659/67570352-bc086300-f763-11e9-81af-f53edbf93b41.png)

**Comment by gilsoncabacazzo** [comment]
It worked my friend

thanks
regards !!

![image](https://user-images.githubusercontent.com/56260092/67571724-0a3d4800-f70b-11e9-862d-3e8879a0c470.png)

**Comment by yuzd** [comment]
@gilsoncabacazzo nice
