### ISSUE TITLE
Using sending emails from httpjob

### ISSUE THREAD

**Issue by gilsoncabacazzo** [yuzd/Hangfire.HttpJob#24]
What do I need to use the sending of emails when an httpjob task was completed, either with errors or successfully.

Attached capture of task settings.
Could you give me a help?
Thank you
Regards

![image](https://user-images.githubusercontent.com/56260092/67578951-e6cdc980-f719-11e9-953d-51bb3bbc0e29.png)

**Comment by yuzd** [comment]
can you check this?（Google Chrome right-click translation）

https://github.com/yuzd/Hangfire.HttpJob/wiki/%E5%A6%82%E4%BD%95%E9%85%8D%E5%90%88%E9%82%AE%E7%AE%B1%E6%9C%8D%E5%8A%A1

**Comment by gilsoncabacazzo** [comment]
I have already configured the mail server.
Are the alerts sent automatically? That is, when a task is completed, is the alert sent?
I ask why I did not receive any alerts when the tasks were finished

![image](https://user-images.githubusercontent.com/56260092/67693403-6230b480-f980-11e9-96b2-862fc742c028.png)


Thanks for the clarification
Regards

**Comment by yuzd** [comment]
@gilsoncabacazzo  SendSucMail value default is  False..do you set it True? 

![image](https://images4.c-ctrip.com/target/zb06190000017zvib8E72.png)

**Comment by yuzd** [comment]
only one recipient, is not necessary to separate it with a comma or some other character.
I suspect there is something wrong with your SMTP server configuration.
Can you test your SMTP server with mailkit yourself by write unit test？

**Comment by gilsoncabacazzo** [comment]
the port is mandatory ?,
I have another application in c # where I only pass the server, username and password, and from that application I get emails

**Comment by yuzd** [comment]
should set port value 

![image](https://images4.c-ctrip.com/target/zb01190000018e2o4F8C2.png)

**Comment by gilsoncabacazzo** [comment]
I already established the port, who would be the sender of the email ??

![1](https://user-images.githubusercontent.com/56260092/67768487-636dea00-fa31-11e9-88dc-7bebc18337e7.PNG)
![2](https://user-images.githubusercontent.com/56260092/67768488-636dea00-fa31-11e9-99ef-401449f9df97.PNG)
![3](https://user-images.githubusercontent.com/56260092/67768490-636dea00-fa31-11e9-8eff-e61d8e5e717d.PNG)

**Comment by gilsoncabacazzo** [comment]
I am registering this exception 
2019-10-29 14: 22: 20.6963 | HttpJobDispatcher.InitSmtpClient The SMTP server does not support authentication.
  LogExtensions.ErrorException => LoggerExecutionWrapper.Log => AspNetCoreLog.Log

**Comment by gilsoncabacazzo** [comment]
it already works, the mail server user was incorrectly configured

![image](https://user-images.githubusercontent.com/56260092/67798289-fcb4f480-fa61-11e9-9d9a-c8d75a1f7f89.png)


Thank you very much for the help always
Regards

**Comment by yuzd** [comment]
success
