### ISSUE TITLE
update hangfire.core to 1.7.7?

### ISSUE THREAD

**Issue by qiang999** [yuzd/Hangfire.HttpJob#25]
您好，近期是否考虑update hangfire.core to 1.7.7,支持.net core 3.0

**Comment by yuzd** [comment]
升级到1.7.7 发现 Hangfire.Tag.Sqlserver 好像有点问题

https://github.com/face-it/Hangfire.Tags/issues/10

**Comment by qiang999** [comment]
我觉得可能是1.7.7项目框架是.net core 3.0,而Hangfire.Tag.Sqlserver为.net core 2.2，兼容性有问题

**Comment by yuzd** [comment]
你用3.0 其实也可以跑1.7.6的。
因为hangfire.core 是 netstand的。下图是hangfire.core的依赖：
![image](https://user-images.githubusercontent.com/16083659/68016738-22dfcc00-fcd0-11e9-94cb-3fef330cdd4d.png)

**Comment by qiang999** [comment]
之前项目是2.2，使用hangfire.httpjob是ok的，最近项目升级3.0，发现添加任务时400错误，执行时500错误，我等会做下测试，看一下是版本兼容问题，还是我代码服务注入有问题

**Comment by yuzd** [comment]
有log说报啥错了吗

**Comment by yuzd** [comment]
我刚更新了 v 2.1.6到nuget。
本地测试了3.0报错问题修复了。

**Comment by qiang999** [comment]
本地已测试OK，谢谢！
