### ISSUE TITLE
只创建单个任务时部分按钮不可用，报错提示“Select One Job Only!”

### ISSUE THREAD

**Issue by miniprince** [yuzd/Hangfire.HttpJob#26]
大牛非常感谢您的分享让我很受益，打算在新项目中使用这个任务调度系统，目前发现在界面如果只有只创建了一个任务，“编辑周期任务”、“暂停或开始”、“带参数运行”等按钮点击会报错，提示“Select One Job Only!”，麻烦修正一下，谢谢！

**Comment by yuzd** [comment]
我check下

**Comment by yuzd** [comment]
我已更新了，https://www.nuget.org/packages/Hangfire.HttpJob/3.0.1

**Comment by miniprince** [comment]
收到，谢谢!

**Comment by yuzd** [comment]
更新后 你记得 chrome 清下缓存

**Comment by miniprince** [comment]
好的，另外请教一下目前只支持Basic基础认证，如果要支持Jwt用Token，我尝试在httpClient增加认证不可行，httpClient.DefaultRequestHeaders.Add("Authorization", "Bearer " + token.access_token);请指教！

**Comment by yuzd** [comment]
可以设置 Header的 ，你看看呢
