### ISSUE TITLE
Http Code 400 not reported as failed task

### ISSUE THREAD

**Issue by AlthalusDGr8** [yuzd/Hangfire.HttpJob#28]
Hi
We noticed that if the service invoked returns an HTTP 400 error, the job is still classifed as successfull.  Is there a way to get these reported as failed (and triggering an error notification)? Thanks

**Comment by yuzd** [comment]
I  will check it today.

**Comment by NicolaAtorino** [comment]
Hello! is there any news on this issue?

**Comment by yuzd** [comment]
Let's discuss together. Are the HTTPResponse Code defaults less than 400 considered wrong?

**Comment by yuzd** [comment]
update to  v3.0.5  . 
httpjob will check if code is less than 400 will reported as failed .

If you want to customize the check rules , please refer to the settings below
![image](https://images4.c-ctrip.com/target/zb021a0000019trh05595.png)
