### ISSUE TITLE
job失败重试

### ISSUE THREAD

**Issue by bjornxiong** [yuzd/Hangfire.HttpJob#29]
Hi,你好，我学习了下你的代码发现job如果失败重试次数、间隔是不可以配置的，[AutomaticRetrySet(Attempts = 3, DelaysInSeconds = new[] { 20, 30, 60 }, LogEvents = true, OnAttemptsExceeded = AttemptsExceededAction.Delete)]
有时api挂了不一定可以在这个时间段重启好，请问下有什么办法可以修改吗？谢谢你的解答。

**Comment by yuzd** [comment]
额，这个问题我之前我想到，目前是写死的
主要是这个标签里面的值不可以外部指定，也许可以重写这个AutomaticRetrySet标签 我得试试

**Comment by bjornxiong** [comment]
好的，谢谢。

**Comment by yuzd** [comment]
已经实现了，请升级到最新版
如下图：

![image](https://images4.c-ctrip.com/target/zb0o1c000001cz7rpC1B4.png)
