### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by matoDakie** [yuzd/Hangfire.HttpJob#3]
[10:01:14 ERR] HttpJobDispatcher.GetJobItem
System.ArgumentException: Context argument should be of type `AspNetCoreDashboardContext`!
参数名: context
   在 Hangfire.Dashboard.AspNetCoreDashboardContextExtensions.GetHttpContext(DashboardContext context)
   在 Hangfire.HttpJob.Server.HttpJobDispatcher.GetJobItem(DashboardContext _context)

**Comment by yuzd** [comment]
2.0版本已解决此问题
