### ISSUE TITLE
mysql添加周期性作业的问题

### ISSUE THREAD

**Issue by xiaoxie1116** [yuzd/Hangfire.HttpJob#30]
用mysql添加周期性作业的时间，到了指定时间执行之后，就会一直不停的往表hangfire_set插数据，而且不删除任务就会一直往里面插数据

**Comment by yuzd** [comment]
能提供不停insert的数据是啥样的么？

**Comment by xiaoxie1116** [comment]
已经解决了，是hangfire_set表没有设置外键关系：（具体的初始化脚本）
CREATE TABLE `hangfire_set` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `Key` varchar(100) NOT NULL,
  `Value` varchar(256) NOT NULL,
  `Score` float NOT NULL,
  `ExpireAt` datetime DEFAULT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE KEY `IX_Set_Key_Value` (`Key`,`Value`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

**Comment by yuzd** [comment]
ok
