### ISSUE TITLE
BackgroundJob.ContinueJobWith in HttpJobs ?

### ISSUE THREAD

**Issue by gilsoncabacazzo** [yuzd/Hangfire.HttpJob#31]
Is it possible to use BackgroundJob.ContinueJobWith with the extension HttpJobs?

I have developed an api website where I have 3 methods, and these must be executed synchronously

Thank you very much for your help
regards

**Comment by yuzd** [comment]
Sorry, I don't quite understand what you mean, If you want to synchronize execution, why not call in a method

**Comment by gilsoncabacazzo** [comment]
Hello  !
Yes, that way I will do it
Anyway thank you very much
regards
