### ISSUE TITLE
只想用控制台,不想用web,可以用这个框架吗?

### ISSUE THREAD

**Issue by fendou** [yuzd/Hangfire.HttpJob#33]

**Comment by yuzd** [comment]
因为本框架就是对于hangfire的一个扩展而已，除了webjob这个功能，控制台的哪个功能点吸引你了？

**Comment by fendou** [comment]
我在开发一个客户端软件,我想用控制台或winform写,把web上的功能用控制台或winform实现,看这个好像不好改......

**Comment by fendou** [comment]
> 因为本框架就是对于hangfire的一个扩展而已，除了webjob这个功能，控制台的哪个功能点吸引你了？

我在开发一个客户端软件,我想用控制台或winform写,把web上的功能用控制台或winform实现,看这个好像不好改......

**Comment by yuzd** [comment]
这个控制台是hangfire的dashbord功能，可以查看hangfire 官网。https://github.com/HangfireIO/Hangfire

**Comment by fendou** [comment]
> 这个控制台是hangfire的dashbord功能，可以查看hangfire 官网。https://github.com/HangfireIO/Hangfire

哦,谢谢了,我去看一下
