### ISSUE TITLE
Concurrent Execute problem

### ISSUE THREAD

**Issue by xyz0822** [yuzd/Hangfire.HttpJob#4]
Cause of hangfire distributelock mechanism as below
```
  private static string GetResource(Job job)
  {         
        return $"{job.Type.ToGenericTypeString()}.{job.Method.Name}";
  }
```
if we put DisableConcurrentExecution attribute to the method we want to method as below
 ```
[AutomaticRetry(Attempts = 3)]
[DisplayName("HttpJob:{1}")]
[DisableConcurrentExecution(1000)]
public static void Excute(HttpJobItem item, string jobName = null, PerformContext context = null)
        {
            try
            {
                context.WriteLine(jobName);
                context.WriteLine(JsonConvert.SerializeObject(item));
                var client = GetHttpClient(item);
                var httpMesage = PrepareHttpRequestMessage(item);
                var httpResponse = client.SendAsync(httpMesage).GetAwaiter().GetResult();
                HttpContent content = httpResponse.Content;
                string result = content.ReadAsStringAsync().GetAwaiter().GetResult();
                context.WriteLine(result);
            }
            catch (Exception ex)
            {
                Logger.ErrorException("HttpJob.Excute", ex);
                context.WriteLine(ex.Message);
            }
}

```

and we create many httpjob to the hangfire，we only got **one distributelock**("**HttpJob.Execute**")，that **our different jobs** become **execute one by one** .not what we expected ,cause we only have one method to execute differenent jobs.

**Comment by yuzd** [comment]
@xyz0822  i found same thing about DisableConcurrentExecution attribute 
https://stackoverflow.com/questions/44447660/hangfire-disableconcurrentexecution-vs-worker-count-1

**DisableConcurrentExecution** is a per job attribute that ensures that two instances of the class/method name **are not running at the same time**

**Comment by yuzd** [comment]
@xyz0822 是加了DisableConcurrentExecution 的话 hangfire才会加锁对吧？

**Comment by xyz0822** [comment]
> @xyz0822 是加了DisableConcurrentExecution 的话 hangfire才会加锁对吧？
是的，sqlserver数据库是通过存储过程来实现串行执行的，mysql有插件是通过数据库表distributedlock来实现

**Comment by yuzd** [comment]
最新版本的已经规避了这个问题。因为采用了自定义的 加锁的key
