### ISSUE TITLE
无法指定任务队列，请问如何处理

### ISSUE THREAD

**Issue by yuanxiongwei** [yuzd/Hangfire.HttpJob#40]
Hangfire.HttpJob.Client.BackgroundJob 不包含 QueueName，无法指定任务执行的任务队列

**Comment by yuanxiongwei** [comment]
是不是HangfireJobClient.AddBackgroundJob 添加的任务无法指定队列？

**Comment by yuzd** [comment]
我看下

**Comment by yuzd** [comment]
> Hangfire.HttpJob.Client.BackgroundJob 不包含 QueueName，无法指定任务执行的任务队列

client已发布新版本
