### ISSUE TITLE
能否限定只能添加指定http job？

### ISSUE THREAD

**Issue by garfage** [yuzd/Hangfire.HttpJob#42]
能否限定只能添加指定http job？
让其只能访问内网job，而不能指定公网地址

**Comment by yuzd** [comment]
请升级到最新版本3.1.7
然后按照下面添加一个 拦截器

![image](https://images4.c-ctrip.com/target/zb0q1g000001h71hq913E.png)

效果如下：
![image](https://images4.c-ctrip.com/target/zb0c1g000001h8ea0CECD.png)
