### ISSUE TITLE
mysql启动面板报错，请问这个缺少的参数是什么导致的

### ISSUE THREAD

**Issue by zhan520g** [yuzd/Hangfire.HttpJob#46]
![image](https://user-images.githubusercontent.com/22271449/83884239-2f049e00-a777-11ea-9b1f-29ba013749eb.png)

**Comment by zhan520g** [comment]
![image](https://user-images.githubusercontent.com/22271449/83884336-4f345d00-a777-11ea-8e2d-a5f451884417.png)

**Comment by zhan520g** [comment]
点击菜单栏就会报第一张图的错

**Comment by zhan520g** [comment]
![image](https://user-images.githubusercontent.com/22271449/83884410-6d9a5880-a777-11ea-823f-84b49053b692.png)

**Comment by yuzd** [comment]
请问你用的是我的demo跑的吗？
mysql版本多少？
