### ISSUE TITLE
代码添加任务的方式貌似无效？

### ISSUE THREAD

**Issue by wdloading** [yuzd/Hangfire.HttpJob#47]
你好
我按照示例，用代码方式添加任务，但实际并未添加，而且我Basic密码特意输入错误都没有异常出现。

api接口返回成功，但是任务列表中没有新增这个任务

![图片](https://user-images.githubusercontent.com/45893014/84933280-3c6f4000-b108-11ea-9835-17432317170f.png)

![图片](https://user-images.githubusercontent.com/45893014/84933451-7dffeb00-b108-11ea-9fd3-15eb2269eb32.png)

**Comment by wdloading** [comment]
我尝试用接口请求方式，一直返回403

![图片](https://user-images.githubusercontent.com/45893014/84934782-632e7600-b10a-11ea-9f5f-892fd06fa112.png)

**Comment by yuzd** [comment]
![image](https://images4.c-ctrip.com/target/0zb6h1200013txl3q3A92.png)

**Comment by yuzd** [comment]
你用client端去添加 判断是否成功 你得看下 result 是多少。调试下

**Comment by wdloading** [comment]
我把basic认证去掉了，但是用client去add任务时返回如下图2
![image](https://user-images.githubusercontent.com/45893014/84985528-7aec1580-b16f-11ea-904e-574639a01178.png)

![image](https://user-images.githubusercontent.com/45893014/84985428-48dab380-b16f-11ea-8f9c-d500554ac7ce.png)

**Comment by wdloading** [comment]
另外，我GET周期性作业没有问题，但是POST就返回403了
![image](https://user-images.githubusercontent.com/45893014/84985842-141b2c00-b170-11ea-920a-3f35c1c6b76e.png)

**Comment by yuzd** [comment]
看下配置是否少了 
https://github.com/yuzd/Hangfire.HttpJob/wiki/00.QickStart
![image](https://images4.c-ctrip.com/target/0zb4u12000173fs2r8B0F.png)

**Comment by wdloading** [comment]
配置有，手工添加OK，就是写代码方式不行，我加下你QQ
![image](https://user-images.githubusercontent.com/45893014/85003870-6583e500-b189-11ea-9f8b-80a77ff46ac6.png)

**Comment by wdloading** [comment]
找到原因了，hangfire和本身的webapi项目方一起了，两个的认证方式出现了冲突，所以返回403
