### ISSUE TITLE
json参数是否支持中文字符

### ISSUE THREAD

**Issue by 573000126** [yuzd/Hangfire.HttpJob#49]
JobName、Data是否中文字符，运行项目执行带参数的job提示错误“Request headers must contain only ASCII characters.”

**Comment by yuzd** [comment]
你是不是header 里面配置了key是中文？

**Comment by 573000126** [comment]
照搬的TestHangfire示例，没有配置过 需要配置吗

**Comment by yuzd** [comment]
找到问题了 我提交了一个新版本 @573000126

**Comment by 573000126** [comment]
老大有交流群吗，我发现删除job有bug ，编辑修改后也有些问题😂

**Comment by yuzd** [comment]
QQ1877682825
