### ISSUE TITLE
如果请求地址里需要带上签名、时间戳这些信息，我该如何配置呢？

### ISSUE THREAD

**Issue by arvinws** [yuzd/Hangfire.HttpJob#50]
大佬，我新增一个周期性作业，在调用api接口时 需要带上签名、时间戳。在配置页面如何加上这些信息，都是动态的参数 不能写固定的值。该如何处理？

**Comment by yuzd** [comment]
如果签名是动态生成(打个比方 当前的时间戳+数据 进行md5)的话
这种 没有办法直接在周期性作业里面进行设置。

但是你若想要在请求数据里面有动态的时间的话是可以用EL表达式的：https://github.com/yuzd/Hangfire.HttpJob/wiki/04.Callback%E5%8A%9F%E8%83%BD%7CEL%E8%A1%A8%E8%BE%BE%E5%BC%8F%E6%9D%A5%E5%8A%A8%E6%80%81%E6%96%AD%E8%A8%80%E6%89%A7%E8%A1%8C%E6%88%90%E5%8A%9F%E8%BF%98%E6%98%AF%E5%A4%B1%E8%B4%A5

可以直接在 #{} 方法里面用DateTime这个变量 这个变量和c#一样的功能

比如

#{DateTime.Now} 代表运行时的当前时间+时分秒
#{DateTime.Today} 代表运行时的当天
#{DateTime.Today.AddDays(-1)} 代表运行时的昨天
#{DateTime.Today.AddDays(1)} 代表运行时的明天

**Comment by arvinws** [comment]
签名信息如果不能在页面上的周期性作业里配置，是否可以在后端直接添加一个周期性作业，带上这些动态的签名信息？大佬有遇到这种情况么，一般怎么解决？

**Comment by arvinws** [comment]
> 如果签名是动态生成(打个比方 当前的时间戳+数据 进行md5)的话
> 
> 这种 没有办法直接在周期性作业里面进行设置。
> 
> 
> 
> 但是你若想要在请求数据里面有动态的时间的话是可以用EL表达式的：https://github.com/yuzd/Hangfire.HttpJob/wiki/04.Callback%E5%8A%9F%E8%83%BD%7CEL%E8%A1%A8%E8%BE%BE%E5%BC%8F%E6%9D%A5%E5%8A%A8%E6%80%81%E6%96%AD%E8%A8%80%E6%89%A7%E8%A1%8C%E6%88%90%E5%8A%9F%E8%BF%98%E6%98%AF%E5%A4%B1%E8%B4%A5
> 
> 
> 
> 可以直接在 #{} 方法里面用DateTime这个变量 这个变量和c#一样的功能
> 
> 
> 
> 比如
> 
> 
> 
> #{DateTime.Now} 代表运行时的当前时间+时分秒
> 
> #{DateTime.Today} 代表运行时的当天
> 
> #{DateTime.Today.AddDays(-1)} 代表运行时的昨天
> 
> #{DateTime.Today.AddDays(1)} 代表运行时的明天
> 
> 


签名信息如果不能在页面上的周期性作业里配置，是否可以在后端直接添加一个周期性作业，带上这些动态的签名信息？大佬有遇到这种情况么，一般怎么解决？

**Comment by yuzd** [comment]
实现方式有很多种，
比如我可以写一个api 去包装一下。在这个api在去实现这些动态的签名。
