### ISSUE TITLE
Docker方式还是挺麻烦，能否提供Redis作为存储的一键安装的docker方式

### ISSUE THREAD

**Issue by Lflying-NRSoft** [yuzd/Hangfire.HttpJob#52]
Docker方式还是挺麻烦，能否提供Redis作为存储的一键安装的docker方式。
因为这个类似我们的工具，我们如果有个想法，希望能非常流畅的开箱即用的方式来搭建一台docker环境。
另外很多场景都需要用到异步任务，比如：订单的处理，处理过程可以分为强依赖和弱依赖的，而弱依赖
一般都可以作为异步操作的，这时候就会将订单处理切分成两个或者多个请求，除了强依赖的第一个请求之后，
其他的都希望用这个组件来帮忙处理，而现在引入这个组件需要额外的数据库，太麻烦了，如果有Redis快速
搭建一套，那就可以让开发人员只聚焦于业务逻辑了。

**Comment by yuzd** [comment]
在wiki我放了有一个mysql作为存储的docker 镜像。

redis 或者是 mysql 或者是 sqlserver 只是hangfire的数据存储。

redis其实也蛮好的，我后面来build一个redis镜像

**Comment by yuzd** [comment]
@Lflying-NRSoft  redis作为存储的一键安装的docker方式 已经搞定了 
https://github.com/yuzd/Hangfire.HttpJob/wiki/000.Docker-Quick-Start
