### ISSUE TITLE
Add recurring job fail

### ISSUE THREAD

**Issue by gilsoncabacazzo** [yuzd/Hangfire.HttpJob#55]
Hello
I am not being able to add a recurring task, I don't know what could be setting wrong.
I attach two images

Might you help me ?

Thank you
![1](https://user-images.githubusercontent.com/56260092/86379050-55bfd280-bc58-11ea-95bb-d68e9bd5cd0c.png)
![2](https://user-images.githubusercontent.com/56260092/86379062-59535980-bc58-11ea-9de2-feb2f1eee495.png)

**Comment by gilsoncabacazzo** [comment]
I am using net core 3.1

**Comment by yuzd** [comment]
can you check this?
![image](https://images4.c-ctrip.com/target/0zb2a12000401v25d5F2C.png)

**Comment by yuzd** [comment]
can you try the new version ? would show detail error when add job failed.

**Comment by gilsoncabacazzo** [comment]
I have set the property to true

![image](https://user-images.githubusercontent.com/56260092/87056441-a5137f00-c1d3-11ea-9089-b11d12c32c72.png)

**Comment by gilsoncabacazzo** [comment]
We recommend using version 3.2.5 of Hangfire.HttpJob ?

I am currently using version 2.2.3

Thanks

**Comment by yuzd** [comment]
if you use new version of hangfire.httpjob.
when you add job fail ,you can get detail err msg.

**Comment by gilsoncabacazzo** [comment]
Thanks !!
