### ISSUE TITLE
关于全局配置的问题

### ISSUE THREAD

**Issue by yanh19930226** [yuzd/Hangfire.HttpJob#56]
建议把这个全局配置什么的去掉，界面可以全局配置，又可以配置文件里面配置，每个任务又可以配置，稍微复杂

**Comment by yanh19930226** [comment]
手动执行周期，钉钉通知不一定会触发

**Comment by yuzd** [comment]
有些是启动的时候要配置的参数，在界面上配置了 ，如果不重新启动的话 也无法生效。
钉钉的问题，清查看wiki
