### ISSUE TITLE
docker 失败是什么原因？

### ISSUE THREAD

**Issue by zhongbodong** [yuzd/Hangfire.HttpJob#57]
![image](https://user-images.githubusercontent.com/28446826/87024754-1b33d800-c20c-11ea-9aca-5a0077a35d11.png)
![image](https://user-images.githubusercontent.com/28446826/87024811-2d157b00-c20c-11ea-9824-0f69bfe3581b.png)

**Comment by yuzd** [comment]
后缀是/job
