### ISSUE TITLE
search engine does not work in dashboard

### ISSUE THREAD

**Issue by gilsoncabacazzo** [yuzd/Hangfire.HttpJob#58]
Task search or filter does not work on recurring task link

Would you need to establish any additional settings?

I attach two images
![a](https://user-images.githubusercontent.com/56260092/87055098-e571fd80-c1d1-11ea-9a7c-7dcfc51cc6da.png)
![b](https://user-images.githubusercontent.com/56260092/87055104-e73bc100-c1d1-11ea-8388-9112d1fd3308.png)

Thanks for the help

Regards

**Comment by gilsoncabacazzo** [comment]
I am using the latest version of Hangfire.HttpJob and the task finder in the recurring tasks menu does not work for me

![image](https://user-images.githubusercontent.com/56260092/87063360-41418400-c1dc-11ea-9e27-d42878a982b2.png)

**Comment by yuzd** [comment]
Is the storage you use oracle？

**Comment by gilsoncabacazzo** [comment]
Yes i use oracle as storage

**Comment by yuzd** [comment]
Sorry, I can't reproduce your error without Oracle environment
