### ISSUE TITLE
不能调用接口进行暂停或开启任务吗

### ISSUE THREAD

**Issue by zhan520g** [yuzd/Hangfire.HttpJob#59]

**Comment by zhan520g** [comment]
我缺个文档， 我想完全通过rest api 来新增 编辑，暂停我的job.

**Comment by yuzd** [comment]
wiki api 有新增，删除

**Comment by zhan520g** [comment]
编辑，暂停，重新开启，木有。这些东西也很有用， 这样那个dashbord就相当于交给运维了。

**Comment by yuzd** [comment]
目前api client端能支持的：
后台任务(backgroundjob)
api 可以新增 可以删除 ，如果想要编辑的话 可以删除在重新建立。我没有找到backgroundjob 可以编辑的接口

周期性任务（RecurringJob）
api 可以新增 可以删除，如果是编辑的话 重新提交新增(保证jobname不变就是更新) 

暂停 开启 周期性job 我认为没有必要用api上操作，在dashbord上不就可以了吗？

**Comment by zhan520g** [comment]
我现在这是把这个功能提供给用户使用。 比如客户用我们的系统， 想暂停他自己创建的任务，或者重新开启。 这个时候，客户不应该操作dashbord

**Comment by zhan520g** [comment]
https://github.com/xuxueli/xxl-job   我们公司在用这个java的调度，就因为他啥都支持，我就觉的很好用。 作为C#开发人员， 我自己的项目，想尽量使用.net core（点个赞）

**Comment by yuzd** [comment]
假设我在client加了暂停和开启的接口。用户在你们的系统 暂停 你怎么记录这个job是暂停或者开启的状态。目前我的client也没有拉取job列表的接口
