### ISSUE TITLE
在mysql8.0数据库上会偶尔出现任务调度不成功

### ISSUE THREAD

**Issue by ghd258** [yuzd/Hangfire.HttpJob#6]
用的这个mysql组件  https://github.com/stulzq/Hangfire.MySql.Core

**Comment by yuzd** [comment]
我还没有用8.0 我看你在他那边提了 我这边就关了哈 。

**Comment by ghd258** [comment]
问题已经解决了，我已经找到原因给作者说了 他升级最新版本就好了；请问下你的代码demo怎么查看Dashboard页面

**Comment by yuzd** [comment]
默认是 5000端口。。启动起来 localhost:5000/job 就是dashbord
