### ISSUE TITLE
执行长时间任务时每次都是在4分钟后取消了任务

### ISSUE THREAD

**Issue by LouieGuo** [yuzd/Hangfire.HttpJob#60]
环境：.net core 3.1
Hangfire.HttpJob 3.1.5
Hangfire.Tags.Mysql 1.0.2

不知是什么原因，已经挺多天出现任务取消，目前也正在排查原因
![image](https://user-images.githubusercontent.com/29138525/88123610-d5104880-cbfd-11ea-9b3e-274a2652f81d.png)
![image](https://user-images.githubusercontent.com/29138525/88123726-16085d00-cbfe-11ea-9563-3e589ceddef9.png)

![image](https://user-images.githubusercontent.com/29138525/88123854-59fb6200-cbfe-11ea-81d3-8382e3f0f325.png)

**Comment by yuzd** [comment]
Mysql链接字符串里面加上usessl=false
