### ISSUE TITLE
Hangfire.Tags.Mysql 变更依赖

### ISSUE THREAD

**Issue by xiangxiren** [yuzd/Hangfire.HttpJob#61]
既然Hangfire.MySql.Core已经不再维护，是否考虑将项目Hangfire.Tags.Mysq依赖Hangfire.MySql.Core变更为依赖Hangfire.MySqlStorage

**Comment by yuzd** [comment]
Hangfire.MySqlStorage是在维护吗

**Comment by xiangxiren** [comment]
> Hangfire.MySqlStorage是在维护吗

在啊

**Comment by yuzd** [comment]
已提交新版本
