### ISSUE TITLE
Cron表达式生成可以设置成秒级么？

### ISSUE THREAD

**Issue by arvinws** [yuzd/Hangfire.HttpJob#62]
![image](https://user-images.githubusercontent.com/43133223/88262579-0de21780-ccfb-11ea-8125-cfea63f40cad.png)

**Comment by yuzd** [comment]
秒级在hangfire redis的话用的比较多，
在sqlserver mysql等数据库上用的话并不能完全保证。所以我用秒级特别少。
等我有空了考虑下吧。
