### ISSUE TITLE
headers是否可以支持Callback表达式

### ISSUE THREAD

**Issue by jinqiang-jiao** [yuzd/Hangfire.HttpJob#65]
hello，
![image](https://user-images.githubusercontent.com/69249069/89417555-67b5f900-d761-11ea-8f17-2711deef4f37.png)
这里只有子job的data可以支持#parent进行传参
是否可以headers也可以支持#parent传参？
谢谢！

**Comment by yuzd** [comment]
应该可以，我看看

**Comment by yuzd** [comment]
![image](https://images4.c-ctrip.com/target/0zb6q12000810whg62926.png)

**Comment by yuzd** [comment]
已更新代码

**Comment by jinqiang-jiao** [comment]
nuget包是否忘记更新了？
![image](https://user-images.githubusercontent.com/69249069/89794305-76355380-db59-11ea-91d8-24f21a64d0f3.png)

**Comment by yuzd** [comment]
抱歉 漏掉了。已补提交nuget

**Comment by jinqiang-jiao** [comment]
hello,
可以帮忙看一下吗?
![image](https://user-images.githubusercontent.com/69249069/89907404-389afe00-dc1f-11ea-8c80-e865faeb7571.png)
json配置如下：
![image](https://user-images.githubusercontent.com/69249069/89907700-92032d00-dc1f-11ea-935c-b0afacdd1249.png)

**Comment by yuzd** [comment]
你脱敏，然后贴下完整的

**Comment by jinqiang-jiao** [comment]
不好意思，最近在忙其他项目，没有及时看到信息

![image](https://user-images.githubusercontent.com/69249069/92300480-ae2f8b00-ef8d-11ea-8eac-59f5775eeaa2.png)
返回json:
![image](https://user-images.githubusercontent.com/69249069/92300502-dcad6600-ef8d-11ea-9245-cb566ee613d0.png)
现在我发现2个问题
1.程序获取token_type
![image](https://user-images.githubusercontent.com/69249069/92300543-6b21e780-ef8e-11ea-9246-5c6f4af6883e.png)
值没有转换成功
2.
"Headers": {
      "Authorization": "#{#parent.token_type}",
 }
报错信息如下：
![image](https://user-images.githubusercontent.com/69249069/92300602-be943580-ef8e-11ea-8776-a64046e55d08.png)

设置为Authorization1没问题，是否Authorization被设为关键字无法处理
辛苦了，谢谢

**Comment by yuzd** [comment]
哦 我找到原因了 目前是针对post请求才会执行SPEL表达式逻辑。我得修改下

**Comment by yuzd** [comment]
![image](https://user-images.githubusercontent.com/16083659/92306332-dd132480-efc0-11ea-94e9-973b53768271.png)
你更新下

**Comment by jinqiang-jiao** [comment]
ok了，谢谢
