### ISSUE TITLE
corn表达式为5秒执行一次，实际执行时间却是15秒

### ISSUE THREAD

**Issue by 656511385** [yuzd/Hangfire.HttpJob#66]
corn表达式为五秒执行的： */5 * * * * ?

但是实际运行的是15秒

**Comment by yuzd** [comment]
这个执行调度的精准度 根据我的经验是和你配置多久扫描一次是有关系的。
对于这个要求很严格的建议用redis 然后这个参数要配置下
![image](https://user-images.githubusercontent.com/16083659/91986885-de91e200-ed5f-11ea-9306-9153f8576636.png)

**Comment by 656511385** [comment]
谢谢，已解决
