### ISSUE TITLE
Problems withs http jobs - HangFire

### ISSUE THREAD

**Issue by RicardoBraga1996** [yuzd/Hangfire.HttpJob#67]
We have the following error when calling an API in hangFire:

**_The error is as follows_**

"Headers": {}
}】System.OperationCanceledException Messgae:The operation was canceled. StackTrace:
at System.Net.Http.HttpClient.HandleFinishSendAsyncError(Exception e, CancellationTokenSource cts) at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts) at Hangfire.HttpJob.Server.HttpJob.Excute(HttpJobItemitem, String jobName, String queuename, Boolean isretry, PerformContext context) 

Running in the Swagger if it works correctly.

I attach the screenshots about these errors. Please if you could help us.

@yuzd , @odinserj @HenryDaniJP88
[
![Error1](https://user-images.githubusercontent.com/44382248/92155987-47c43480-edf6-11ea-9b01-526e74d6d036.PNG)
![Error2](https://user-images.githubusercontent.com/44382248/92155995-498df800-edf6-11ea-9262-ba5c79d94fe0.PNG)
![Swagger_Run_Ok](https://user-images.githubusercontent.com/44382248/92156001-4abf2500-edf6-11ea-84cf-d031477b26f7.PNG)
![Swagger_Run_Ok_2](https://user-images.githubusercontent.com/44382248/92156003-4b57bb80-edf6-11ea-8fcb-f6ef8888fbf3.PNG)

](url)

**Comment by yuzd** [comment]
What is the timeout you set

**Comment by RicardoBraga1996** [comment]
The timeout is 5000 and the Hangfire.Https version is 2.2.3.

I attach the screenshots about the version and timeout on the HangFire dashboard.

![TimeOut](https://user-images.githubusercontent.com/44382248/92248385-975a3d00-ee96-11ea-8c94-8cc818296c42.png)
![Version_Hangfire HttpJob (2 2 3)](https://user-images.githubusercontent.com/44382248/92248390-99240080-ee96-11ea-86ae-3129e108eb4b.png)

También hago referencia a la clase -> Hangfire.HttpJob/Server/HttpJob.cs: https://github.com/yuzd/Hangfire.HttpJob/blob/a02290f88f60659b712badea1c03f74ff34846e9/Hangfire.HttpJob/Server/HttpJob.cs#L165

**Comment by yuzd** [comment]
Want to confirm a few points
1. What is the response time of your api when you use swagger to test
2. The default timeout is 5 seconds, if your api is indeed timed out, that error message will appear。
You try to increase the timeout to see if it works
3. Update to the last version of this lib if you can.
4.

**Comment by yuzd** [comment]
I close this issue temporarily  Please leave me message if you have any questions
