### ISSUE TITLE
更换MySQL驱动后，是否与原有表结构兼容?

### ISSUE THREAD

**Issue by xyz0822** [yuzd/Hangfire.HttpJob#69]
如题

**Comment by yuzd** [comment]
https://github.com/yuzd/Hangfire.HttpJob/issues/61

升级的话特别要注意：
如果你的db 已经是 hangfire_ 开头的话 需要在代码中把 tabprefix 由 hangfire 修改成 hangfire_ 否则会出问题

**Comment by xyz0822** [comment]
好的，多谢
