### ISSUE TITLE
新增循环任务时一直提示Forbidden

### ISSUE THREAD

**Issue by i542873057** [yuzd/Hangfire.HttpJob#7]
没有设置basic验证，但是在调用**HangfireJobClient.AddRecurringJob**方法时返回结果一直是Forbidden
把相同的参数复制到界面操作却是可以的
>部分代码

`var result = HangfireJobClient.AddRecurringJob("http://localhost:52500/job", new RecurringJob()
                        {
                            JobName = taskname,
                            Method = "Get",
                            Url = "http://localhost:52500/hangfire/addprocedurejob",
                            SendSucMail = false,
                            Cron = corn
                        });
`

**Comment by yuzd** [comment]
AddRecurringJob 方法 后面好像还有一个参数是 设置 basic参数的 你看看呢

**Comment by i542873057** [comment]
> AddRecurringJob 方法 后面好像还有一个参数是 设置 basic参数的 你看看呢

试过了，还是不行。   这个错误提示是未授权的提示吗？

**Comment by yuzd** [comment]
你传了 BasicUserName 和 BasicPassword了 还提示错误？

**Comment by i542873057** [comment]
> 你传了 BasicUserName 和 BasicPassword了 还提示错误？

是的设置了用户名和密码传过去了也提示这个错误 
把密码去掉传空值也是这个错误。。。有点神奇了

**Comment by i542873057** [comment]
> 你传了 BasicUserName 和 BasicPassword了 还提示错误？
这是startup中的配置（没有密码的配置）
`app.UseHangfireServer();
            var hangfireStartUpPath = "/job";
            app.UseHangfireDashboard(hangfireStartUpPath);
`

**Comment by yuzd** [comment]
加QQ 1877682825

**Comment by yuzd** [comment]
![image](https://user-images.githubusercontent.com/16083659/59342871-37c9bc00-8d3d-11e9-8598-0c782244e326.png)
