### ISSUE TITLE
定时任务【查看状态】问题

### ISSUE THREAD

**Issue by wangboshun** [yuzd/Hangfire.HttpJob#70]
新建的定时任务，点击【查看状态】是这个弹窗。
请问一下，怎样的任务才可以用？
我还没有明白jobAgent怎么用的。

**Comment by yuzd** [comment]
https://github.com/yuzd/Hangfire.HttpJob/wiki/03.HttpJob.Agent%E7%BB%84%E4%BB%B6%E4%BB%8B%E7%BB%8D%E4%BB%A5%E5%8F%8A%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8

这个是使用教程，不明白的可以提出来
