### ISSUE TITLE
JobAgent无法运行，代码如下，望老大指点

### ISSUE THREAD

**Issue by 348465303** [yuzd/Hangfire.HttpJob#71]
![image](https://user-images.githubusercontent.com/17284334/93065227-07dd3700-f6ab-11ea-8fa3-4f07eb03b111.png)
![image](https://user-images.githubusercontent.com/17284334/93065300-1d526100-f6ab-11ea-8b00-b2d14cfe962b.png)

**Comment by yuzd** [comment]
配置的classType的完整名称不对导致的。对照wiki上关于jobagent的 AgentClass参数

**Comment by 348465303** [comment]
谢谢老大
