### ISSUE TITLE
Is it support DingTalk notifacation

### ISSUE THREAD

**Issue by zhujiancc** [yuzd/Hangfire.HttpJob#72]

**Comment by yuzd** [comment]
https://github.com/yuzd/Hangfire.HttpJob/wiki/%E9%85%8D%E7%BD%AE%E9%92%89%E9%92%89%E5%8F%91%E9%80%81job%E6%89%A7%E8%A1%8C%E7%BB%93%E6%9E%9C%E9%80%9A%E7%9F%A5
