### ISSUE TITLE
发布到linux，根据Id搜索失败。（本地window上是正常的）

### ISSUE THREAD

**Issue by zhujiancc** [yuzd/Hangfire.HttpJob#76]
不清楚是不是当前系统语言不一致导致的
linux ： en-Us
window: zh-CN

![image](https://user-images.githubusercontent.com/19665595/93990676-fc31f480-fdbd-11ea-8b64-b456b65ca5ee.png)
![image](https://user-images.githubusercontent.com/19665595/93990617-e9b7bb00-fdbd-11ea-81df-37526d051dc7.png)

**Comment by yuzd** [comment]
这个问题我没有在linux在现出来。。。

**Comment by zhujiancc** [comment]
我用虚拟机 复现不出来了...  
可能和公司内网的环境有点关系 ，
