### ISSUE TITLE
Failed 这里搜索完的显示式样异常【HttpAgent Job】

### ISSUE THREAD

**Issue by zhujiancc** [yuzd/Hangfire.HttpJob#77]
![image](https://user-images.githubusercontent.com/19665595/93991938-7f077f00-fdbf-11ea-9cbb-7ad2e79c389e.png)

![image](https://user-images.githubusercontent.com/19665595/93992019-9fcfd480-fdbf-11ea-80bd-bf03bb528092.png)

**Comment by zhujiancc** [comment]
httpjob.js line: 1135
这段代码有问题,   remove 把 job detail给去掉了，  导致样式变形了
```
var table = $('.table-responsive').find('table');
var filtered = ($(".page-header").text().substr(0, 4) === '定期作业' || $(".page-header").text().substr(0, 4) === 'Recu') ? $(table).find('input.js-jobs-list-checkbox[value*=' + keyword + ']').closest('tr') : $(table).find('a[class=job-method]:contains(' + keyword + ')').closest('tr');
$(table).find('tbody tr').remove();
$(table).find('tbody').append(filtered);
```

**Comment by yuzd** [comment]
昨晚提交的代码修复这个了，还有timer没搞定，其他的差不多了，你下载我最新代码看看
