### ISSUE TITLE
怎样集成HangfireDashboard？

### ISSUE THREAD

**Issue by Cloud33** [yuzd/Hangfire.HttpJob#8]
好像文档并不是很明确，只需要引用 Hangfire.HttpJob？
但我发现，这个包依赖也太多了吧！不支持.net framework？
![image](https://user-images.githubusercontent.com/8787198/59416965-f565b500-8df8-11e9-8869-aa7073476815.png)

**Comment by yuzd** [comment]
不支持 netframework！是netcore下的。
Hangfire.HttpJob 是针对Hangfire的一个扩展包
Hangfire.Console 也是针对Hangfire的一个开源扩展包 用到它是因为执行HttpJob的日志记录
Hangfire.Tags 也是针对Hangfire的一个开源扩展包，用到它是因为对HttpJob进行分组查询
Newtonsoft.Json 这个不用说了吧
HttpClientFactory 这个包是我开发的一个开源的安全使用HttpClient的组件
Hangfire.AspNetCore 这个是Hangfire核心组件
MailKit是如果你配置HttpJob执行失败发送邮件通知用的

以上每个包都是必须的，至于如何使用，你可以看下 源码有一个 TestHangfire这个项目。 直接可以运行起来的！

**Comment by yuzd** [comment]
如果是用mysql作为存储的话
引用 Hangfire.HttpJob
Hangfire.Tags.Mysql
Hangfire.MySql.Core
Hangfire.Dashboard.BasicAuthorization 这4个就ok了

**Comment by Cloud33** [comment]
好的，谢谢解答。

**Comment by yuzd** [comment]
发布了新版 支持了 netframework 4.6 + 。。你看看？

**Comment by Cloud33** [comment]
依赖太多了了，对我来说，我现在打算使用Hangfire 定时调用http请求的方式去做。
感谢支持。
