### ISSUE TITLE
问题整理：

### ISSUE THREAD

**Issue by zhujiancc** [yuzd/Hangfire.HttpJob#81]
### 优化
* HttpJob：添加一个HttpAgent的健康检查机制，
     * 处理processing的问题【失败长期驻留】
     * 监控HttpAgent状态【异常通知】
* HttpJob：失败的提示 ， 最好有一个已读的逻辑
* HttpJob：DingTalk模板自定义【现有的模板 最好给一个导航到错误地址的URI】
* HttpJob：添加job失败时提示不够友好
### BUG
* redis 失败列表排序错误
* jobContext.Console ： Color 设置无效
* 任务已经结束了，但是任务执行状态，卡到这里不动了，一直停留在processing 【偶尔发生，最好有回收或者纠察的机制】
![image](https://user-images.githubusercontent.com/19665595/94768623-855eb200-03e2-11eb-9f40-e445c02c335d.png)
* Hang任务，暂停的时候throw error。job面板显示任务执行成功 ，【生成了两条记录，一个success，一个failed，应该是顺序问题】
![image](https://user-images.githubusercontent.com/19665595/94768646-8ee81a00-03e2-11eb-8ff7-3e6b2c3fa2b4.png)

**Comment by yuzd** [comment]
## HttpJob：DingTalk模板自定义【现有的模板 最好给一个导航到错误地址的URI】

这个目前就是有这个功能的
![image](https://user-images.githubusercontent.com/16083659/94818253-7a327300-0430-11eb-9673-8e05d23c7ede.png)

## HttpJob：添加job失败时提示不够友好 

这个下个版本会修复
![image](https://user-images.githubusercontent.com/16083659/94818296-89192580-0430-11eb-8f30-b7a63df88b94.png)

## redis 失败列表排序错误
这个是redis storage的排序问题，我这边好像无法处理

## Hang任务，暂停的时候throw error。job面板显示任务执行成功 ，【生成了两条记录，一个success，一个failed，应该是顺序问题】

这个下个版本会修复

**Comment by yuzd** [comment]
## jobContext.Console ： Color 设置无效
这个问题已找到 下个问题会修复

**Comment by yuzd** [comment]
## 任务已经结束了，但是任务执行状态，卡到这里不动了，一直停留在processing 【偶尔发生，最好有回收或者纠察的机制】
这个还没有复现

**Comment by yuzd** [comment]
HttpJob：添加一个HttpAgent的健康检查机制，
处理processing的问题【失败长期驻留】
监控HttpAgent状态【异常通知】

这个待思考

**Comment by yuzd** [comment]
HttpJob：失败的提示 ， 最好有一个已读的逻辑

失败的增加一个筛选 是否已读？貌似不太好实现的感觉
