### ISSUE TITLE
如何关闭hangfire stats日志？

### ISSUE THREAD

**Issue by garfage** [yuzd/Hangfire.HttpJob#85]
如题，打开hangfire页面一直会输出 HTTP POST /hangfire/stats responded 200 in 15.5392 ms 这种日志，请问如何配置能够关闭它？

**Comment by yuzd** [comment]
这个属于aspnetcore的日志级别 需要设置下 
![image](https://user-images.githubusercontent.com/16083659/96568442-8a849200-12fa-11eb-8c66-04ed713f5bcd.png)

**Comment by garfage** [comment]
改了，不过还是没有用

**Comment by yuzd** [comment]
不会吧。你有没有改对啊。你百度下看看呢

**Comment by yuzd** [comment]
![image](https://user-images.githubusercontent.com/16083659/96842579-cb59e380-147f-11eb-9567-99e0f584f1b5.png)
可能你是debug运行的话
你release的话就不会打印了
在Program.cs里面设置
