### ISSUE TITLE
使用windowsserver作为服务端执行时，http任务出现异常

### ISSUE THREAD

**Issue by feigaogit** [yuzd/Hangfire.HttpJob#86]
使用windowsserver作为服务端执行时，正常任务没问题，但http任务出现下面的异常，请问怎么解决
![image](https://user-images.githubusercontent.com/18181270/97520146-811fb780-19d5-11eb-836f-79ed3d618719.png)

这是正常任务：
![image](https://user-images.githubusercontent.com/18181270/97520209-a1e80d00-19d5-11eb-8a4d-07d21d8020aa.png)

**Comment by yuzd** [comment]
请使用最新版试试

**Comment by liyouzhuo** [comment]
我的windowsserver部署完毕后无法启动，提示错误5：拒绝访问

**Comment by yuzd** [comment]
> 我的windowsserver部署完毕后无法启动，提示错误5：拒绝访问
有尝试先本地跑github中的demo吗？
请帖下具体的报错信息

**Comment by liyouzhuo** [comment]
> > 我的windowsserver部署完毕后无法启动，提示错误5：拒绝访问
> > 有尝试先本地跑github中的demo吗？
> > 请帖下具体的报错信息

![QQ截图20240624201340](https://github.com/yuzd/Hangfire.HttpJob/assets/32318669/74098009-8eae-484a-9713-bd99a9fe0b90)
1、demo运行完全没有问题
2、
![image](https://github.com/yuzd/Hangfire.HttpJob/assets/32318669/46fd59d8-4b81-4040-95bb-379984da1893)
我在原测试项目基础上直接添加UseWindowsService，想将它作为Windows Server来部署调度端，执行：sc create HangfireHttpJobService binPath= "D:\Hangfire.HttpJob.Service"时，Windows Server可以部署成功
![image](https://github.com/yuzd/Hangfire.HttpJob/assets/32318669/b31bde91-5429-40b5-96dc-0f3a62f3d537)
但是当我尝试启动它时，提示：
![image](https://github.com/yuzd/Hangfire.HttpJob/assets/32318669/e7374782-89e1-42ee-9907-608c2c1ffb78)

**Comment by liyouzhuo** [comment]
@yuzd 佬，有空麻烦帮我看下是哪里出的问题哈，谢谢🙏

**Comment by liyouzhuo** [comment]
> > 我的windowsserver部署完毕后无法启动，提示错误5：拒绝访问
> > 有尝试先本地跑github中的demo吗？
> > 请帖下具体的报错信息

sorry啊，大佬，是我在部署服务的时候搞错了，我的问题，打扰了打扰了
