### ISSUE TITLE
How to delete a job (background or recurring)?

### ISSUE THREAD

**Issue by fatkulamri** [yuzd/Hangfire.HttpJob#9]

**Comment by yuzd** [comment]
![image](https://user-images.githubusercontent.com/16083659/60407910-257dc800-9bef-11e9-85a5-e41f606f4b9d.png)

**Comment by flyliao** [comment]
提问应该是：如果我添加了一个周期性作业，如果我某状态下执行完了，怎么通过系统自动删除，而不是到dashbord去手动删除

**Comment by fatkulamri** [comment]
I want delete it from client rest API, not from Dashboard

**Comment by yuzd** [comment]
@fatkulamri 
new release update!
#13

**Comment by fatkulamri** [comment]
Thank you @yuzd
