### ISSUE TITLE
IIS部署问题

### ISSUE THREAD

**Issue by Gy-Liang** [yuzd/Hangfire.HttpJob#90]
你好！我在iis部署无法在公网访问，在服务器本地却是正常的，使用相同端口的空网站可以正常在外网访问访问，将其改到httpjob项目上后又无法正常外网访问。希望得到您的一些帮助，谢谢！

**Comment by yuzd** [comment]
其他项目部署在iis可以吗？

**Comment by Gy-Liang** [comment]
已经解决了，为了方便测试我注释掉了身份认证部分代码，导致本地正常访问，但是远程失败。

**Comment by yuzd** [comment]
好的 建议还是部署为windows服务。
硬要在iis的话 需要设置下 iis alwaysrunning 且 设置不回收
