### ISSUE TITLE
配置了DefaultTimeZone，写入数据库的时间与系统时间不一致

### ISSUE THREAD

**Issue by iufun** [yuzd/Hangfire.HttpJob#97]
1. 在配置文件中设置了，"DefaultTimeZone": "Asia/Shanghai"
2. 数据库所在系统的时区，Wed, 16 Dec 2020 20:49:03 +0800
写入数据库中的时间为：“2020-12-16 12:42:05.0638130”，却与系统时间不一致，怎么处理？

**Comment by yuzd** [comment]
配置的时区代表的是hangfire调度job用的时区。
你说的写入数据库的是指的hangfire自身数据里的时间吗？
hangfire自身数据里的时间存储用的是utc。

**Comment by iufun** [comment]
明白了

**Comment by iufun** [comment]
明白了
