### ISSUE TITLE
执行周期问题，每5秒执行一次

### ISSUE THREAD

**Issue by yesheng586969** [yuzd/Hangfire.HttpJob#98]
发现没5秒执行一次，差不多在循环了1分钟后就开始休眠了，等一会又好了
![image](https://user-images.githubusercontent.com/19927365/102598066-6c9aa880-4156-11eb-9e01-0804362bc65c.png)

**Comment by yuzd** [comment]
https://github.com/yuzd/Hangfire.HttpJob/issues/66

**Comment by yuzd** [comment]
请查看上面的issue
总结来说 应该是hangfire server调度的扫描周期导致的。
